In [1]:
# 본 코드의 목적
# daily_stockwise_dict / year_no 에 보관된 일별_1, 일별_2 피클 파일들을 모두 모아서
# 연 단위의 통합 df를 만든다

In [2]:
# 거래일을 가져오는 과정

In [3]:
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import datetime

In [4]:
kospi_list_df = fdr.StockListing('KOSDAQ')

In [5]:
test_symbol_list = []
for i in range(5):
    test_symbol_list.append(kospi_list_df['Symbol'].values[i])

test_symbol_list

['060310', '054620', '265520', '211270', '013720']

In [6]:
target_year = '2021'

In [7]:
full_date_df = fdr.DataReader(test_symbol_list[1], target_year)

In [8]:
full_date_df

             Open   High    Low  Close   Volume    Change
Date
2021-01-04   8220   8270   7960   8000   300316 -0.025579
2021-01-05   7970   8100   7870   7900   190388 -0.012500
2021-01-06   7940   7980   7590   7670   471365 -0.029114
2021-01-07   7700   7730   7600   7650   178284 -0.002608
2021-01-08   7650   7720   7470   7500   274988 -0.019608
...           ...    ...    ...    ...      ...       ...
2021-09-10  18300  18800  17800  18350   111977  0.005479
2021-09-13  18350  18400  16700  17150   129109 -0.065395
2021-09-14  17450  22100  17050  18650  1059719  0.087464
2021-09-15  18350  18550  17500  18150   156797 -0.026810
2021-09-16  18150  18150  17400  17950   112692 -0.011019

[178 rows x 6 columns]

In [9]:
raw_tradingdays = list(full_date_df.index.values)

In [10]:
tradingdays = [int(pd.to_datetime(td).strftime('%Y%m%d')) for td in raw_tradingdays]

In [11]:
daily_folder_dir = './daily_stockwise_dict/'+target_year

In [12]:
import sys

from PyQt5.QtWidgets import *

app = QApplication(sys.argv)

from kiwoom.kiwoom import *

save_list = []

kiwoom = Kiwoom(save_list)

로그인에 성공하였습니다.

1. 현재 로그인 상태 확인
2. 사용자 정보 조회
3. 예수금 조회
4. 계좌 잔고 조회
5. 미체결 내역 조회
6. 종목 리스트 조회
7. 일별 투자자별 매수 매도 종목 조회
Q. 프로그램 종료
P. Kiwoom 객체를 보존한 채로 종료
=> p

In [13]:
stock_code_list = kiwoom.get_code_list_by_market('10') # '10'이 코스닥

In [47]:
stockwise_list_dict = {}
for stock_code in stock_code_list:
    stockwise_list_dict[stock_code] = []

In [15]:
import pandas as pd

In [16]:
import pickle

In [17]:
# 여기서 일자별로 순회

In [18]:
# 외국인: 1
# 기관: 2
# 연기금: 8

In [48]:
for curr_tradingday in tradingdays:
    daily_file_1_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_1.pickle'
    daily_file_2_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_2.pickle'
    with open(daily_file_1_dir, 'rb') as fr:
        stockwise_dict_1 = pickle.load(fr)
    with open(daily_file_2_dir, 'rb') as fr:
        stockwise_dict_2 = pickle.load(fr)
    for stock_code in stock_code_list:
        if stock_code in list(stockwise_dict_1.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_1[stock_code][2])
        elif stock_code in list(stockwise_dict_2.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_2[stock_code][2])
        else:
            stockwise_list_dict[stock_code].append(0)

FileNotFoundError: [Errno 2] No such file or directory: './daily_stockwise_dict/2021/daily_stockwise_dict_20210916_1.pickle'

In [49]:
year_daily_df = pd.DataFrame(columns = stock_code_list, index = tradingdays[:177])

In [50]:
for stock_code in stock_code_list:
    year_daily_df[stock_code] = stockwise_list_dict[stock_code]

In [51]:
year_daily_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,0,0,0,0,0,0,0,-5210,0,0,...,785,15,0,0,0,0,0,0,0,0
20210105,0,0,0,0,0,0,-8,-4517,0,0,...,806,10,0,0,0,0,0,0,0,0
20210106,0,0,0,0,0,0,0,-2658,0,0,...,-433,0,0,0,0,0,0,0,0,0
20210107,0,0,0,0,0,0,0,-1807,0,0,...,137,0,0,0,4,0,0,0,6,0
20210108,0,0,0,0,0,0,0,-1689,0,0,...,-67,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210909,0,0,0,0,0,0,0,-942,0,0,...,0,-78,0,-149,0,0,0,0,0,0
20210910,0,0,0,0,0,0,0,-118,0,0,...,0,-251,0,-185,0,0,0,0,0,0
20210913,0,0,0,0,0,0,0,-2467,0,0,...,-35,-343,0,-100,0,0,0,0,0,0
20210914,0,0,0,0,0,0,0,-91,0,0,...,0,-1,0,-598,0,0,0,0,0,0
20210915,0,0,0,0,0,0,0,-1019,0,0,...,0,0,0,-3,0,0,0,0,0,0

In [25]:
import os

In [26]:
os.getcwd()

'C:\\Users\\박형진\\Desktop\\pythonTrading'

In [52]:
dm_dir = os.path.join(os.getcwd(), 'DM')

In [53]:
# 기관: institution
# 연기금: pension
# 외국인: foreigner

In [54]:
curr_dm_dir = os.path.join(dm_dir, 'DM_kosdaq_institution_buy')

In [43]:
import pickle

In [44]:
year_daily_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,0,-25,14,0,-12,-72,-15,-1116,-12,-1,...,-765,9,0,0,196,-16,3,79,-1,0
20210105,0,-11,-69,0,144,-44,12,-4505,6,8,...,-585,223,0,0,-385,-6,-3,-260,-3,0
20210106,20,-35,-9,0,-15,-75,51,-745,-60,71,...,280,-2,0,0,-417,1,34,8,-2,0
20210107,3,10,17,0,-342,27,-22,-1567,10,-25,...,-427,-46,0,0,-756,33,8,-16,-3,0
20210108,-31,-114,79,0,-119,-76,-35,-3993,0,-46,...,-2997,-52,0,0,10,-57,-26,8,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210909,-8,6,47,0,-68,54,27,-1638,36,-441,...,285,8,0,-494,-46,22,15,104,-40,0
20210910,0,-18,-10,0,15,24,23,-1825,8,-76,...,-330,-202,0,74,-58,59,17,29,114,0
20210913,-8,-23,-34,0,-61,-12,-21,-3642,-28,-111,...,-636,149,0,-126,-88,-39,-2,98,-25,0
20210914,2,5,64,0,-13,19,11,-344,26,14,...,147,218,0,-42,16,48,11,-81,-69,0
20210915,-6,-8,-6,0,-38,-14,-14,-415,-30,3,...,2330,-35,0,809,14,9,7,-19,-125,0

In [55]:
for month in ['09']:
    monthly_df = year_daily_df.loc[int(target_year+month+'01'):int(target_year+month+'99')]
    print(len(monthly_df))
    with open(os.path.join(curr_dm_dir,(target_year+month))+'.pickle', 'wb') as f:
        pickle.dump(monthly_df, f)

20
18
22
22
19
22
22
21

In [71]:
twomonth_cum_df.sort_values(by=20210824, axis=1, ascending=False)

,293490,237690,141080,086520,222800,131970,214450,263750,272290,278280,...,112040,034230,046890,319660,078340,240810,035760,253450,383310,036490
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210818,30594.0,32490.0,23801.0,23831.0,21717.0,17175.0,17991.0,9008.0,17795.0,36432.0,...,-15595.0,-21598.0,-18104.0,-21331.0,-20772.0,-26986.0,-8537.0,-23063.0,-60006.0,-22800.0
20210819,32184.0,33176.0,23379.0,26328.0,22463.0,18449.0,18314.0,14164.0,16644.0,31750.0,...,-15647.0,-21408.0,-19007.0,-21820.0,-21871.0,-26326.0,-15712.0,-24118.0,-59832.0,-21551.0
20210820,38644.0,33689.0,24472.0,26282.0,22954.0,18994.0,18076.0,17246.0,15822.0,25057.0,...,-14152.0,-19469.0,-19028.0,-21577.0,-20807.0,-24113.0,-19528.0,-25060.0,-64502.0,-26229.0
20210823,39649.0,34231.0,24748.0,26437.0,22844.0,19028.0,19167.0,18169.0,15916.0,18780.0,...,-15117.0,-19454.0,-19220.0,-20863.0,-20696.0,-22925.0,-20797.0,-26073.0,-66369.0,-50999.0
20210824,40524.0,34218.0,26815.0,25722.0,24535.0,18803.0,18671.0,17853.0,15996.0,15852.0,...,-15404.0,-19118.0,-19587.0,-20560.0,-21957.0,-23240.0,-23988.0,-25994.0,-66127.0,-66661.0

In [ ]:
# loader를 위한 코드

In [59]:
# 장 내 주식 리스트를 가지고 온 뒤