In [1]:
# 본 코드의 목적
# daily_stockwise_dict / year_no 에 보관된 일별_1, 일별_2 피클 파일들을 모두 모아서
# 연 단위의 통합 df를 만든다

In [2]:
# 거래일을 가져오는 과정

In [3]:
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import datetime

In [4]:
kospi_list_df = fdr.StockListing('KOSDAQ')

In [5]:
kospi_list_df

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
5,211270,KOSDAQ,AP위성,통신 및 방송 장비 제조업,위성통신 단말기,2016-03-04,12월,류장수,http://www.apsi.co.kr,서울특별시
53,013720,KOSDAQ,CBI,자동차 신품 부품 제조업,엔진부품,1993-12-29,12월,오경원,http://www.cheongbo.co.kr,인천광역시
...,...,...,...,...,...,...,...,...,...,...
7129,024060,KOSDAQ,흥구석유,기타 전문 도매업,휘발유등,1994-12-07,12월,김상우,NaN,대구광역시
7130,010240,KOSDAQ,흥국,특수 목적용 기계 제조업,굴삭기 Roller 및 형단조품,2009-05-12,12월,류명준,http://www.heungkuk.co.kr,충청남도
7131,189980,KOSDAQ,흥국에프엔비,비알코올음료 및 얼음 제조업,"과일음료(에이드베이스, 스무디, 착즙쥬스 등)",2015-08-07,12월,"박철범, 오길영",http://www.hyungkuk.com,서울특별시
7136,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호 (각자대표)",http://www.heerim.com,서울특별시
7137,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [6]:
test_symbol_list = []
for i in range(5):
    test_symbol_list.append(kospi_list_df['Symbol'].values[i])

test_symbol_list

['060310', '054620', '265520', '211270', '013720']

In [7]:
target_year = '2021'

In [8]:
full_date_df = fdr.DataReader(test_symbol_list[1], target_year)

In [9]:
full_date_df

             Open   High    Low  Close  Volume    Change
Date
2021-01-04   8220   8270   7960   8000  300316 -0.025579
2021-01-05   7970   8100   7870   7900  190388 -0.012500
2021-01-06   7940   7980   7590   7670  471365 -0.029114
2021-01-07   7700   7730   7600   7650  178284 -0.002608
2021-01-08   7650   7720   7470   7500  274988 -0.019608
...           ...    ...    ...    ...     ...       ...
2021-08-24  19450  19650  18650  19000   98776 -0.007833
2021-08-25  19000  19650  18700  19450   59159  0.023684
2021-08-26  19550  19950  19250  19350   47887 -0.005141
2021-08-27  19250  19550  18900  19300   32603 -0.002584
2021-08-30  19300  19350  18950  19350   42689  0.002591

[165 rows x 6 columns]

In [10]:
raw_tradingdays = list(full_date_df.index.values)

In [11]:
tradingdays = [int(pd.to_datetime(td).strftime('%Y%m%d')) for td in raw_tradingdays]

In [12]:
daily_folder_dir = './daily_stockwise_dict/'+target_year

In [13]:
import sys

from PyQt5.QtWidgets import *

app = QApplication(sys.argv)

from kiwoom.kiwoom import *

save_list = []

kiwoom = Kiwoom(save_list)

로그인에 성공하였습니다.

1. 현재 로그인 상태 확인
2. 사용자 정보 조회
3. 예수금 조회
4. 계좌 잔고 조회
5. 미체결 내역 조회
6. 종목 리스트 조회
7. 일별 투자자별 매수 매도 종목 조회
Q. 프로그램 종료
P. Kiwoom 객체를 보존한 채로 종료
=> p

In [14]:
stock_code_list = kiwoom.get_code_list_by_market('10') # '10'이 코스닥

In [15]:
stockwise_list_dict = {}
for stock_code in stock_code_list:
    stockwise_list_dict[stock_code] = []

In [16]:
import pandas as pd

In [17]:
import pickle

In [18]:
# 여기서 일자별로 순회

In [19]:
for curr_tradingday in tradingdays[:-1]:
    daily_file_1_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_1.pickle'
    daily_file_2_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_2.pickle'
    with open(daily_file_1_dir, 'rb') as fr:
        stockwise_dict_1 = pickle.load(fr)
    with open(daily_file_2_dir, 'rb') as fr:
        stockwise_dict_2 = pickle.load(fr)
    for stock_code in stock_code_list:
        if stock_code in list(stockwise_dict_1.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_1[stock_code][2])
        elif stock_code in list(stockwise_dict_2.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_2[stock_code][2])
        else:
            stockwise_list_dict[stock_code].append(0)

In [20]:
institution_year_daily_df = pd.DataFrame(columns = stock_code_list, index = tradingdays[:-1])

In [21]:
for stock_code in stock_code_list:
    institution_year_daily_df[stock_code] = stockwise_list_dict[stock_code]

In [22]:
institution_year_daily_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,0,0,0,0,0,0,0,-5210,0,0,...,785,15,0,0,0,0,0,0,0,0
20210105,0,0,0,0,0,0,-8,-4517,0,0,...,806,10,0,0,0,0,0,0,0,0
20210106,0,0,0,0,0,0,0,-2658,0,0,...,-433,0,0,0,0,0,0,0,0,0
20210107,0,0,0,0,0,0,0,-1807,0,0,...,137,0,0,0,4,0,0,0,6,0
20210108,0,0,0,0,0,0,0,-1689,0,0,...,-67,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210823,0,0,0,0,0,-7,0,1381,0,0,...,0,7,0,47,0,0,0,-2337,-68,0
20210824,0,0,0,0,0,-77,0,326,0,0,...,91,324,0,-113,0,0,0,-46,-19,0
20210825,0,0,0,0,0,0,0,644,0,0,...,-94,-499,0,40,0,0,0,-37,1,0
20210826,0,0,0,0,0,0,0,-3808,0,0,...,0,-466,0,-342,0,0,0,-154,0,0
20210827,0,0,0,0,0,0,0,-428,0,0,...,0,-282,0,-218,0,0,0,-419,0,0

In [23]:
stockwise_list_dict = {}
for stock_code in stock_code_list:
    stockwise_list_dict[stock_code] = []

In [24]:
for curr_tradingday in tradingdays[:-1]:
    daily_file_1_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_1.pickle'
    daily_file_2_dir = daily_folder_dir+'/daily_stockwise_dict_'+str(curr_tradingday)+'_2.pickle'
    with open(daily_file_1_dir, 'rb') as fr:
        stockwise_dict_1 = pickle.load(fr)
    with open(daily_file_2_dir, 'rb') as fr:
        stockwise_dict_2 = pickle.load(fr)
    for stock_code in stock_code_list:
        if stock_code in list(stockwise_dict_1.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_1[stock_code][8])
        elif stock_code in list(stockwise_dict_2.keys()):
            stockwise_list_dict[stock_code].append(stockwise_dict_2[stock_code][8])
        else:
            stockwise_list_dict[stock_code].append(0)

In [25]:
pension_year_daily_df = pd.DataFrame(columns = stock_code_list, index = tradingdays[:-1])

In [26]:
for stock_code in stock_code_list:
    pension_year_daily_df[stock_code] = stockwise_list_dict[stock_code]

In [27]:
pension_year_daily_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,0,0,0,0,0,0,0,-612,0,0,...,760,0,0,0,0,0,0,0,0,0
20210105,0,0,0,0,0,0,0,469,0,0,...,514,0,0,0,0,0,0,0,0,0
20210106,0,0,0,0,0,0,0,23,0,0,...,-366,0,0,0,0,0,0,0,0,0
20210107,0,0,0,0,0,0,0,-692,0,0,...,-128,0,0,0,0,0,0,0,0,0
20210108,0,0,0,0,0,0,0,-166,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210823,0,0,0,0,0,0,0,-10,0,0,...,0,0,0,5,0,0,0,1,0,0
20210824,0,0,0,0,0,0,0,-361,0,0,...,0,-43,0,0,0,0,0,0,0,0
20210825,0,0,0,0,0,0,0,11,0,0,...,0,-49,0,2,0,0,0,0,0,0
20210826,0,0,0,0,0,0,0,-1453,0,0,...,0,0,0,-338,0,0,0,0,0,0
20210827,0,0,0,0,0,0,0,-262,0,0,...,0,0,0,-189,0,0,0,0,0,0

In [28]:
institution_buy_3dr_df = institution_year_daily_df.rolling(3).sum()
pension_buy_3dr_df = pension_year_daily_df.rolling(3).sum()

In [77]:
tradingday_dict = {}
for day in tradingdays[3:-1]:
    tradingday_dict[day]=[]
    daily_institution_buy_3dr_df = institution_buy_3dr_df.loc[day:day]
    daily_pension_buy_3dr_df = pension_buy_3dr_df.loc[day:day]
    institution_sorted_amount = sorted(daily_institution_buy_3dr_df.values.tolist()[0], reverse=True)
    institution_topten_amount = institution_sorted_amount[5:20]
    pension_sorted_amount = sorted(daily_pension_buy_3dr_df.values.tolist()[0], reverse=True)
    pension_topten_amount = pension_sorted_amount[5:20]
    for stock_code in stock_code_list:
        if (daily_institution_buy_3dr_df[stock_code].values[0] in institution_topten_amount) and (daily_pension_buy_3dr_df[stock_code].values[0] in pension_topten_amount):
            tradingday_dict[day].append(stock_code)

In [78]:
tradingday_dict

{20210107: ['104480',
  '215200',
  '218410',
  '237880',
  '278280',
  '297090',
  '299900'],
 20210108: ['035760', '145020', '215200', '297090'],
 20210111: ['080160', '145020', '215200'],
 20210112: ['061970', '067160', '122870', '160550', '299900'],
 20210113: ['061970', '093320', '160550', '299900'],
 20210114: ['041510', '095340', '145020', '160550', '306040'],
 20210115: ['041510', '080160', '092730', '095340', '145020', '306040'],
 20210118: ['099320', '166090'],
 20210119: ['080160', '095340', '099320', '299900'],
 20210120: ['068760', '141080'],
 20210121: ['054780', '141080'],
 20210122: ['015750', '074600', '319660'],
 20210125: ['034230', '035760', '069080', '226950', '237690', '253450'],
 20210126: ['034230', '141080', '226950'],
 20210127: ['066970', '080160'],
 20210128: ['017890', '066970', '214150', '226950', '241840'],
 20210129: ['182400', '213420', '241840'],
 20210201: ['033640', '036490', '145020', '182400', '214450', '237690'],
 20210202: ['068760', '145020', '182400', '214450'],
 20210203: ['028300', '068760', '214450'],
 20210204: ['122870', '144510', '160550', '235980'],
 20210205: ['078890', '089980', '144510', '160550', '235980'],
 20210208: ['052710', '144510', '213420'],
 20210209: ['035080', '089980'],
 20210210: ['112040', '265520', '293490'],
 20210215: ['056190', '102710', '131290'],
 20210216: ['078150', '095700', '102710', '215200'],
 20210217: ['078150', '215200', '300120'],
 20210218: ['078150', '265520', '290510', '321820'],
 20210219: ['056190', '083500', '138610'],
 20210222: ['036200', '194700'],
 20210223: ['194700', '298540'],
 20210224: ['039200', '089600', '112040', '141080', '200130', '235980'],
 20210225: ['036200', '084370', '141080', '144510', '213420'],
 20210226: ['084370', '086900', '101160', '141080', '144510', '213420'],
 20210302: ['034230',
  '036200',
  '036490',
  '101160',
  '141080',
  '213420',
  '240810'],
 20210303: ['036200',
  '036490',
  '084370',
  '101160',
  '122870',
  '141080',
  '144510'],
 20210304: ['054780', '086900', '141080', '241840'],
 20210305: ['054780', '086900', '101160', '160550'],
 20210308: ['034230', '054780', '086900'],
 20210309: ['095610', '160550', '215200'],
 20210310: ['216050', '297090'],
 20210311: ['213420', '216050', '297090', '357780'],
 20210312: ['100090', '108320', '144510', '216050', '323990'],
 20210315: ['039030',
  '100090',
  '122870',
  '144510',
  '215000',
  '216050',
  '323990'],
 20210316: ['056190', '091990', '100090', '213420', '237690'],
 20210317: ['058470',
  '084370',
  '088800',
  '108320',
  '200130',
  '215000',
  '240810'],
 20210318: ['058470', '060250', '084370', '091990', '240810'],
 20210319: ['060720', '237690', '241840'],
 20210322: ['039030', '060720', '074600', '085370'],
 20210323: ['039030', '074600', '213420', '290650'],
 20210324: ['039030',
  '060250',
  '074600',
  '084370',
  '213420',
  '214450',
  '235980',
  '272290'],
 20210325: ['035900',
  '039030',
  '084370',
  '091990',
  '100090',
  '200130',
  '235980'],
 20210326: ['039030', '067160', '084370', '141080', '200130', '272290'],
 20210329: ['067160',
  '099320',
  '141080',
  '178320',
  '240810',
  '241710',
  '272290'],
 20210330: ['039200',
  '067160',
  '074600',
  '099320',
  '178320',
  '241840',
  '321820'],
 20210331: ['039200', '054780', '178320', '215200', '272290'],
 20210401: ['253450', '272290', '321820'],
 20210402: ['060150', '084370', '086520', '278280'],
 20210405: ['036200', '036490', '084370', '278280'],
 20210406: ['036200', '064290', '078340', '247540', '253450'],
 20210407: ['036200', '064290', '189300', '306040', '340570'],
 20210408: ['036200', '036890', '060150', '064290', '189300', '272290'],
 20210409: ['036200', '039200', '078340', '115960', '241840'],
 20210412: ['060150', '115960', '240810', '319660'],
 20210413: ['025900',
  '095700',
  '141080',
  '278280',
  '294090',
  '299030',
  '319660',
  '334970'],
 20210414: ['025900',
  '086900',
  '095700',
  '096530',
  '145020',
  '156100',
  '278280',
  '299030'],
 20210415: ['036490', '060250', '156100', '178320', '278280'],
 20210416: ['025900', '066970', '078600', '178320', '278280'],
 20210419: ['025900',
  '036930',
  '060250',
  '086520',
  '096530',
  '141080',
  '240810',
  '247540',
  '253450'],
 20210420: ['036930',
  '039200',
  '084370',
  '086520',
  '095700',
  '141080',
  '247540',
  '278280'],
 20210421: ['005290',
  '039200',
  '046890',
  '086520',
  '095700',
  '278280',
  '357780'],
 20210422: ['039200', '067160', '095610', '101160', '226950'],
 20210423: ['046890', '067310', '086520', '099190', '145020'],
 20210426: ['025900', '053030', '060250', '074600'],
 20210427: ['096240', '213420', '237690'],
 20210428: ['063170', '096240', '213420', '237880'],
 20210429: ['084110', '237880', '950220'],
 20210430: ['096240', '237880'],
 20210503: ['036930'],
 20210504: ['078600', '237690', '237880', '319660'],
 20210506: ['145020', '194480', '240810'],
 20210507: ['145020', '194480', '243070', '297090', '319660'],
 20210510: ['000250', '091990', '145020', '240810'],
 20210511: ['000250'],
 20210512: ['000250', '151860', '194700', '263750', '267980', '306040'],
 20210513: ['096530', '194700', '215000', '263750', '267980'],
 20210514: ['041830', '194700', '200130', '215000'],
 20210517: ['041830', '056190', '080160', '144510', '145020', '200130'],
 20210518: ['034230', '089030', '200130'],
 20210520: ['034230',
  '036490',
  '039030',
  '056190',
  '066970',
  '096530',
  '200130'],
 20210521: ['039030', '056190', '200130'],
 20210524: ['056190', '078340', '213420'],
 20210525: ['112040', '213420', '214450'],
 20210526: ['034230',
  '036930',
  '078340',
  '084650',
  '214450',
  '272290',
  '352480'],
 20210527: ['034230',
  '036930',
  '048260',
  '084650',
  '196170',
  '214150',
  '352480'],
 20210528: ['036930', '084650', '144510', '196170', '247540', '383310'],
 20210531: ['051500', '122870', '144510', '247540'],
 20210601: ['352480'],
 20210602: ['080160', '213420', '222040'],
 20210603: ['090460', '213420', '272290', '278280', '357780'],
 20210604: ['074600', '106240', '272290', '278280', '357780'],
 20210607: ['015750', '247540'],
 20210608: ['035900', '067000', '196170', '213420', '243840'],
 20210609: ['035900', '067000', '213420', '272290', '278280'],
 20210610: ['048260', '068760', '214150', '272290'],
 20210611: ['035760', '068760', '091990', '196170', '214150', '272290'],
 20210614: ['035760',
  '035900',
  '041510',
  '066970',
  '067000',
  '196170',
  '214150'],
 20210615: ['035760',
  '035900',
  '096530',
  '196170',
  '214150',
  '243840',
  '263750'],
 20210616: ['064760', '089600', '263750', '293490'],
 20210617: ['039560', '068760', '214150', '287410'],
 20210618: ['035900', '060250', '064760', '122870', '214150', '272290'],
 20210621: ['035760',
  '060250',
  '065350',
  '096530',
  '122870',
  '141080',
  '265520',
  '272290',
  '278280'],
 20210622: ['035760', '035900', '108320', '145020', '265520', '278280'],
 20210623: ['039030',
  '060250',
  '065350',
  '104480',
  '108320',
  '141080',
  '278280'],
 20210624: ['039030',
  '060250',
  '065350',
  '068760',
  '090460',
  '104480',
  '108320',
  '122870'],
 20210625: ['036930',
  '039030',
  '091990',
  '101490',
  '104480',
  '145020',
  '196170'],
 20210628: ['015750', '036490', '090460', '104480', '126700', '196170'],
 20210629: ['145020', '196170', '214450', '237690', '293490', '317330'],
 20210630: ['039200', '126700', '222800'],
 20210701: ['025900', '035760', '090460', '110790', '222800', '226950'],
 20210702: ['036490', '064550', '090460', '222800', '226950', '235980'],
 20210705: ['039030',
  '064550',
  '086900',
  '131970',
  '226950',
  '235980',
  '247540'],
 20210706: ['063170', '064550', '141080', '214150'],
 20210707: ['144510', '196170', '214150'],
 20210708: ['064550', '066970', '272290'],
 20210709: ['039030', '064550', '263050', '263750', '272290'],
 20210712: ['196170'],
 20210713: ['025900', '060250', '066970', '196170'],
 20210714: ['023160', '063170', '067000', '100090'],
 20210715: ['086900', '090460', '101490', '131970', '214450', '230360'],
 20210716: ['086900', '090460', '108320', '122870', '214450'],
 20210719: ['048260', '090460', '214450'],
 20210720: ['031390', '088800', '230360', '241840'],
 20210721: ['088800', '214450', '230360', '237690', '241840', '293780'],
 20210722: ['036200',
  '036830',
  '064290',
  '101160',
  '131970',
  '160550',
  '237690',
  '293780'],
 20210723: ['036200', '036830', '064290', '214450', '235980', '298540'],
 20210726: ['036200', '048260', '064290', '214450', '263750'],
 20210727: ['030190', '036200', '074600', '214450', '319660'],
 20210728: ['005290', '319660'],
 20210729: ['067160', '074600', '088800', '101160'],
 20210730: ['000250', '096240', '194700', '317330'],
 20210802: ['000250', '214450', '278280'],
 20210803: ['090460', '144510', '213420', '294570'],
 20210804: ['084650', '144510'],
 20210805: ['084370', '084650', '294570'],
 20210806: ['035900', '196170', '213420', '222800', '272290', '356860'],
 20210809: ['086520', '272290', '294570'],
 20210810: ['068240'],
 20210811: ['025900', '035900', '122870'],
 20210812: ['035900', '214450', '222800'],
 20210813: ['036890', '131970', '222800', '228670', '278280'],
 20210817: ['039200', '131970', '228670', '237690'],
 20210818: ['039200', '095340', '100090', '228670', '237690'],
 20210819: ['214450', '222800'],
 20210820: ['039030', '089980', '214450', '222800'],
 20210823: ['039030', '131970', '214450'],
 20210824: ['035900', '039030', '089980', '214450'],
 20210825: ['039030', '039200', '214450'],
 20210826: ['039030', '039200', '060720', '106240', '196170', '214450'],
 20210827: ['039030', '091990', '122870', '214450', '241840']}

In [31]:
close_price_df = pd.read_csv("close_price_20210104_20210827.csv", index_col=0)

close_price_df = pd.DataFrame(columns = stock_code_list, index = tradingdays[:-1])

close_price_df

def parse_date(str_timestamp):
    return int(str_timestamp[:4]+str_timestamp[5:7]+str_timestamp[8:10])

for idx, stock_code in enumerate(stock_code_list):
    print(idx)
    tmp_df = fdr.DataReader(stock_code, target_year)['Close']
    tmp_df.index = [parse_date(x) for x in tmp_df.index.astype(str)]
    close_price_df[stock_code].loc[tmp_df.index[:-1]] = tmp_df.loc[tmp_df.index[:-1]]

In [32]:
close_price_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,235,623,314,951,569,1970,1430,81800,9050,2090,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,235,622,314,951,573,2010,1430,78700,9100,2080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,234,617,314,951,587,1975,1435,79200,8990,2105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,234,619,316,951,600,1970,1420,78000,9100,2100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,227,624,316,951,584,1930,1410,75600,8920,2065,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210823,182,544,320,951,697,1690,1365,59200,13400,2800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210824,180,550,323,951,711,1725,1390,59200,14450,2885,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210825,185,552,326,951,709,1730,1390,61500,14400,2975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210826,186,553,335,951,731,1755,1400,55400,14250,3015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210827,184,553,333,951,720,1750,1415,54900,14950,2915,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

close_price_df.to_csv('close_price_20210104_20210827.csv', index = True)

In [33]:
return_df = ((close_price_df - close_price_df.shift(1))/close_price_df.shift(1))*100

In [34]:
return_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,0.000000,-0.160514,0.000000,0.0,0.702988,2.030457,0.000000,-3.789731,0.552486,-0.478469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,-0.425532,-0.803859,0.000000,0.0,2.443281,-1.741294,0.349650,0.635324,-1.208791,1.201923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,0.000000,0.324149,0.636943,0.0,2.214651,-0.253165,-1.045296,-1.515152,1.223582,-0.237530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,-2.991453,0.807754,0.000000,0.0,-2.666667,-2.030457,-0.704225,-3.076923,-1.978022,-1.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20210823,9.638554,4.615385,2.564103,0.0,2.650957,2.114804,5.405405,5.525847,3.474903,-1.060071,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210824,-1.098901,1.102941,0.937500,0.0,2.008608,2.071006,1.831502,0.000000,7.835821,3.035714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210825,2.777778,0.363636,0.928793,0.0,-0.281294,0.289855,0.000000,3.885135,-0.346021,3.119584,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210826,0.540541,0.181159,2.760736,0.0,3.102962,1.445087,0.719424,-9.918699,-1.041667,1.344538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210827,-1.075269,0.000000,-0.597015,0.0,-1.504788,-0.284900,1.071429,-0.902527,4.912281,-3.316750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
tradingday_return_dict = {}
for day in tradingdays[3:-1]:
    tradingday_return_dict[day]=[]
    daily_institution_buy_3dr_df = institution_buy_3dr_df.loc[day:day]
    daily_pension_buy_3dr_df = pension_buy_3dr_df.loc[day:day]
    institution_sorted_amount = sorted(daily_institution_buy_3dr_df.values.tolist()[0], reverse=True)
    institution_topten_amount = institution_sorted_amount[5:20]
    pension_sorted_amount = sorted(daily_pension_buy_3dr_df.values.tolist()[0], reverse=True)
    pension_topten_amount = pension_sorted_amount[5:20]
    for stock_code in stock_code_list:
        daily_return_df = return_df.loc[day:day]
        if daily_return_df[stock_code].values[0] > 0:
            continue
        if (daily_institution_buy_3dr_df[stock_code].values[0] in institution_topten_amount) and (daily_pension_buy_3dr_df[stock_code].values[0] in pension_topten_amount):
            tradingday_return_dict[day].append(stock_code)

In [90]:
tradingday_return_dict

{20210107: ['215200'],
 20210108: [],
 20210111: ['145020'],
 20210112: [],
 20210113: ['061970'],
 20210114: ['160550'],
 20210115: ['041510', '080160', '095340', '145020', '306040'],
 20210118: ['166090'],
 20210119: ['080160', '095340'],
 20210120: ['068760'],
 20210121: ['141080'],
 20210122: ['319660'],
 20210125: ['253450'],
 20210126: ['034230'],
 20210127: ['080160'],
 20210128: ['017890', '066970', '214150', '226950'],
 20210129: ['213420', '241840'],
 20210201: ['145020'],
 20210202: ['068760', '214450'],
 20210203: ['068760', '214450'],
 20210204: ['122870', '160550'],
 20210205: ['144510'],
 20210208: ['052710', '144510', '213420'],
 20210209: ['035080', '089980'],
 20210210: [],
 20210215: [],
 20210216: [],
 20210217: [],
 20210218: ['078150', '265520', '321820'],
 20210219: ['138610'],
 20210222: [],
 20210223: ['194700'],
 20210224: ['089600', '112040', '200130'],
 20210225: [],
 20210226: ['084370', '101160', '141080', '144510', '213420'],
 20210302: ['213420'],
 20210303: ['144510'],
 20210304: ['086900', '141080'],
 20210305: [],
 20210308: ['034230', '054780', '086900'],
 20210309: ['095610'],
 20210310: ['216050'],
 20210311: ['297090', '357780'],
 20210312: ['323990'],
 20210315: ['100090', '215000', '216050', '323990'],
 20210316: [],
 20210317: ['058470'],
 20210318: ['091990', '240810'],
 20210319: ['237690', '241840'],
 20210322: [],
 20210323: ['039030', '290650'],
 20210324: [],
 20210325: ['039030', '084370', '200130', '235980'],
 20210326: ['039030', '084370'],
 20210329: ['067160', '141080', '240810'],
 20210330: ['099320', '178320', '321820'],
 20210331: ['054780', '178320', '215200'],
 20210401: ['253450', '272290', '321820'],
 20210402: ['060150'],
 20210405: [],
 20210406: ['036200', '247540'],
 20210407: ['340570'],
 20210408: ['036200', '036890', '064290', '272290'],
 20210409: ['036200', '241840'],
 20210412: ['115960', '319660'],
 20210413: ['141080', '299030', '319660', '334970'],
 20210414: ['095700', '096530', '145020'],
 20210415: ['036490', '060250'],
 20210416: ['178320', '278280'],
 20210419: ['060250', '253450'],
 20210420: ['084370', '141080', '247540'],
 20210421: ['005290', '039200', '278280', '357780'],
 20210422: ['039200', '095610', '226950'],
 20210423: ['145020'],
 20210426: ['053030', '060250'],
 20210427: ['213420', '237690'],
 20210428: ['063170', '096240', '213420'],
 20210429: ['237880', '950220'],
 20210430: [],
 20210503: ['036930'],
 20210504: ['078600', '237690', '237880', '319660'],
 20210506: ['145020'],
 20210507: ['243070', '319660'],
 20210510: [],
 20210511: ['000250'],
 20210512: ['263750', '306040'],
 20210513: ['096530', '215000', '267980'],
 20210514: [],
 20210517: ['145020', '200130'],
 20210518: [],
 20210520: ['096530'],
 20210521: ['039030', '056190', '200130'],
 20210524: ['056190', '078340', '213420'],
 20210525: [],
 20210526: ['214450', '352480'],
 20210527: ['196170', '352480'],
 20210528: ['036930', '144510', '383310'],
 20210531: ['144510', '247540'],
 20210601: ['352480'],
 20210602: [],
 20210603: ['357780'],
 20210604: ['278280', '357780'],
 20210607: [],
 20210608: [],
 20210609: ['035900'],
 20210610: [],
 20210611: ['272290'],
 20210614: ['035760', '041510', '067000'],
 20210615: ['035760', '096530', '196170'],
 20210616: ['263750', '293490'],
 20210617: [],
 20210618: ['064760'],
 20210621: ['035760', '065350', '122870', '272290'],
 20210622: ['035900', '145020', '278280'],
 20210623: ['108320', '141080'],
 20210624: ['060250', '104480', '108320', '122870'],
 20210625: ['036930', '039030', '091990', '145020'],
 20210628: ['015750', '090460', '126700', '196170'],
 20210629: ['196170', '214450', '317330'],
 20210630: ['126700'],
 20210701: ['025900', '110790'],
 20210702: ['090460', '222800', '235980'],
 20210705: [],
 20210706: ['141080', '214150'],
 20210707: ['196170'],
 20210708: ['066970'],
 20210709: ['039030', '064550', '263050', '272290'],
 20210712: ['196170'],
 20210713: ['196170'],
 20210714: ['067000'],
 20210715: ['131970', '230360'],
 20210716: ['086900', '090460', '108320', '214450'],
 20210719: ['048260', '090460', '214450'],
 20210720: ['031390', '088800', '230360'],
 20210721: ['088800', '230360', '237690'],
 20210722: ['160550', '237690'],
 20210723: ['064290', '235980'],
 20210726: ['036200', '064290', '214450', '263750'],
 20210727: ['319660'],
 20210728: ['319660'],
 20210729: ['067160', '101160'],
 20210730: ['096240', '194700', '317330'],
 20210802: ['278280'],
 20210803: ['294570'],
 20210804: ['084650'],
 20210805: ['084370'],
 20210806: ['356860'],
 20210809: [],
 20210810: ['068240'],
 20210811: ['025900', '035900', '122870'],
 20210812: [],
 20210813: ['131970', '222800', '228670', '278280'],
 20210817: ['039200', '131970', '228670'],
 20210818: ['100090', '237690'],
 20210819: ['214450', '222800'],
 20210820: ['039030', '214450'],
 20210823: ['131970'],
 20210824: [],
 20210825: ['039200', '214450'],
 20210826: ['039030', '039200', '196170'],
 20210827: ['122870', '214450', '241840']}

In [91]:
# 단순히 당일 오르고 내림을 계산해보자
up_cnt = 0
down_cnt = 0
for tradingday in tradingday_return_dict.keys():
    daily_top_amount_stock_code = tradingday_return_dict[tradingday]
    for stock_code in daily_top_amount_stock_code:
        daily_stock_return = return_df[stock_code][tradingday]
        if np.isnan(daily_stock_return):
            continue
        elif daily_stock_return > 0:
            up_cnt += 1
        elif daily_stock_return < 0:
            down_cnt += 1
        else:
            continue

In [92]:
print(up_cnt)
print(down_cnt)

0
235

In [121]:
# 단순히 다음날 오르고 내림을 계산해보자
up_cnt = 0
down_cnt = 0
for tradingday in tradingday_return_dict.keys():
    daily_top_amount_stock_code = tradingday_return_dict[tradingday]
    for stock_code in daily_top_amount_stock_code:
        tomorrow_index = tradingdays.index(tradingday)+3
        if tomorrow_index >=len(tradingdays)-1:
            continue
        daily_stock_return = return_df[stock_code][tradingdays[tomorrow_index]]
        if np.isnan(daily_stock_return):
            continue
        elif daily_stock_return > 0:
            up_cnt += 1
        elif daily_stock_return < 0:
            down_cnt += 1
        else:
            continue

In [122]:
print(up_cnt)

129

In [123]:
print(down_cnt)

113

In [105]:
tradingday_dict.keys()

dict_keys([20210111, 20210112, 20210113, 20210114, 20210115, 20210118, 20210119, 20210120, 20210121, 20210122, 20210125, 20210126, 20210127, 20210128, 20210129, 20210201, 20210202, 20210203, 20210204, 20210205, 20210208, 20210209, 20210210, 20210215, 20210216, 20210217, 20210218, 20210219, 20210222, 20210223, 20210224, 20210225, 20210226, 20210302, 20210303, 20210304, 20210305, 20210308, 20210309, 20210310, 20210311, 20210312, 20210315, 20210316, 20210317, 20210318, 20210319, 20210322, 20210323, 20210324, 20210325, 20210326, 20210329, 20210330, 20210331, 20210401, 20210402, 20210405, 20210406, 20210407, 20210408, 20210409, 20210412, 20210413, 20210414, 20210415, 20210416, 20210419, 20210420, 20210421, 20210422, 20210423, 20210426, 20210427, 20210428, 20210429, 20210430, 20210503, 20210504, 20210506, 20210507, 20210510, 20210511, 20210512, 20210513, 20210514, 20210517, 20210518, 20210520, 20210521, 20210524, 20210525, 20210526, 20210527, 20210528, 20210531, 20210601, 20210602, 20210603, 20210604, 20210607, 20210608, 20210609, 20210610, 20210611, 20210614, 20210615, 20210616, 20210617, 20210618, 20210621, 20210622, 20210623, 20210624, 20210625, 20210628, 20210629, 20210630, 20210701, 20210702, 20210705, 20210706, 20210707, 20210708, 20210709, 20210712, 20210713, 20210714, 20210715, 20210716, 20210719, 20210720, 20210721, 20210722, 20210723, 20210726, 20210727, 20210728, 20210729, 20210730, 20210802, 20210803, 20210804, 20210805, 20210806, 20210809, 20210810, 20210811, 20210812, 20210813, 20210817, 20210818, 20210819, 20210820, 20210823, 20210824, 20210825, 20210826, 20210827])