In [1]:
# 거래일을 가져오는 과정

In [2]:
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import datetime

In [3]:
kospi_list_df = fdr.StockListing('KOSPI')

In [4]:
test_symbol_list = []
for i in range(5):
    test_symbol_list.append(kospi_list_df['Symbol'].values[i])

test_symbol_list

['095570', '006840', '152100', '295820', '253150']

In [5]:
full_date_df = fdr.DataReader(test_symbol_list[1], '2021')

In [6]:
full_date_df

             Open   High    Low  Close  Volume    Change
Date
2021-01-04  25900  25900  25200  25250   92861  0.003976
2021-01-05  25200  25200  24750  25050   88941 -0.007921
2021-01-06  25050  25550  24900  24900   66138 -0.005988
2021-01-07  24950  25250  24850  25200   94211  0.012048
2021-01-08  25200  25750  25000  25350  132698  0.005952
...           ...    ...    ...    ...     ...       ...
2021-08-09  28700  29000  28000  28450   35182 -0.010435
2021-08-10  28450  28450  27450  27750   31327 -0.024605
2021-08-11  27750  27950  27450  27700   16931 -0.001802
2021-08-12  27500  28450  27500  27650   12702 -0.001805
2021-08-13  27650  27800  27250  27350    3894 -0.010850

[155 rows x 6 columns]

In [7]:
raw_tradingdays = list(full_date_df.index.values)

In [8]:
tradingdays = [int(pd.to_datetime(td).strftime('%Y%m%d')) for td in raw_tradingdays]

In [9]:
import sys

from PyQt5.QtWidgets import *

app = QApplication(sys.argv)

from kiwoom.kiwoom import *

save_list = []

kiwoom = Kiwoom(save_list)

In [15]:
sum_start_date = 20210610
sum_end_date = 20210709

In [16]:
stockwise_dict = {}

In [17]:
target_start_date = sum_start_date
target_end_date = sum_end_date
target_price_or_volume = 1 # 금액: 1, 수량: 2
target_net_or_buy_or_sale = 0 # 순매수: 0, 매수: 1, 매도: 2
target_unit_code = 1 # 0: 천 주, 1: 단 주

In [18]:
stock_code_list = kiwoom.get_code_list_by_market('10') # '10'이 코스닥

In [19]:
stock_code_list

['900110',
 '900270',
 '900260',
 '900290',
 '900300',
 '900310',
 '900340',
 '000250',
 '000440',
 '001000',
 '001540',
 '001810',
 '001840',
 '002230',
 '002290',
 '002680',
 '002800',
 '003100',
 '003310',
 '003380',
 '003800',
 '004590',
 '004650',
 '004780',
 '005160',
 '005290',
 '005670',
 '005710',
 '005860',
 '005990',
 '006050',
 '006140',
 '006580',
 '006620',
 '006730',
 '006910',
 '006920',
 '007330',
 '007370',
 '007390',
 '007530',
 '007680',
 '007720',
 '007770',
 '007820',
 '008290',
 '008370',
 '008470',
 '008830',
 '009300',
 '009520',
 '009620',
 '009730',
 '009780',
 '010170',
 '010240',
 '010280',
 '010470',
 '011040',
 '011080',
 '011320',
 '011370',
 '011560',
 '012340',
 '012620',
 '012700',
 '012790',
 '012860',
 '013030',
 '013120',
 '013310',
 '013720',
 '013810',
 '013990',
 '014100',
 '014190',
 '014200',
 '014470',
 '014570',
 '014620',
 '014940',
 '014970',
 '015710',
 '015750',
 '016100',
 '016250',
 '016600',
 '016670',
 '016790',
 '016920',
 '017000',
 '017250',
 '017480',
 '017510',
 '017650',
 '017890',
 '018000',
 '018120',
 '018290',
 '018310',
 '018620',
 '018680',
 '018700',
 '019010',
 '019210',
 '019540',
 '019550',
 '019570',
 '019590',
 '019660',
 '019770',
 '019990',
 '020180',
 '020400',
 '020710',
 '021040',
 '021045',
 '021080',
 '021320',
 '021650',
 '021880',
 '022100',
 '022220',
 '023160',
 '023410',
 '023440',
 '023460',
 '023600',
 '023760',
 '023770',
 '023790',
 '023900',
 '023910',
 '024060',
 '024120',
 '024740',
 '024800',
 '024810',
 '024830',
 '024840',
 '024850',
 '024880',
 '024910',
 '024940',
 '024950',
 '025320',
 '025440',
 '025550',
 '025770',
 '025870',
 '025880',
 '025900',
 '025950',
 '025980',
 '026040',
 '026150',
 '026910',
 '027040',
 '027050',
 '027360',
 '027580',
 '027710',
 '027830',
 '028080',
 '028300',
 '029480',
 '029960',
 '030190',
 '030350',
 '030520',
 '030530',
 '030960',
 '031310',
 '031330',
 '031390',
 '031510',
 '031860',
 '031980',
 '032080',
 '032190',
 '032280',
 '032300',
 '032500',
 '032540',
 '032580',
 '032620',
 '032680',
 '032685',
 '032750',
 '032790',
 '032800',
 '032820',
 '032850',
 '032860',
 '032940',
 '032960',
 '032980',
 '033050',
 '033100',
 '033110',
 '033130',
 '033160',
 '033170',
 '033200',
 '033230',
 '033290',
 '033310',
 '033320',
 '033340',
 '033430',
 '033500',
 '033540',
 '033560',
 '033600',
 '033640',
 '033790',
 '033830',
 '034230',
 '034810',
 '034940',
 '034950',
 '035080',
 '035200',
 '035290',
 '035460',
 '035600',
 '035610',
 '035620',
 '035760',
 '035810',
 '035890',
 '035900',
 '036000',
 '036010',
 '036030',
 '036090',
 '036120',
 '036170',
 '036180',
 '036190',
 '036200',
 '036480',
 '036490',
 '036540',
 '036560',
 '036620',
 '036630',
 '036640',
 '036670',
 '036690',
 '036710',
 '036800',
 '036810',
 '036830',
 '036890',
 '036930',
 '037030',
 '037070',
 '037230',
 '037330',
 '037350',
 '037370',
 '037400',
 '037440',
 '037460',
 '037760',
 '037950',
 '038010',
 '038060',
 '038070',
 '038110',
 '038160',
 '038290',
 '038340',
 '038390',
 '038460',
 '038500',
 '038530',
 '038540',
 '038620',
 '038680',
 '038870',
 '038880',
 '038950',
 '039010',
 '039020',
 '039030',
 '039200',
 '039230',
 '039240',
 '039290',
 '039310',
 '039340',
 '039420',
 '039440',
 '039560',
 '039610',
 '039670',
 '039740',
 '039830',
 '039840',
 '039860',
 '039980',
 '040160',
 '040300',
 '040350',
 '040420',
 '040610',
 '040910',
 '041020',
 '041140',
 '041190',
 '041440',
 '041460',
 '041510',
 '041520',
 '041590',
 '041830',
 '041910',
 '041920',
 '041930',
 '041960',
 '042000',
 '042040',
 '042110',
 '042370',
 '042420',
 '042500',
 '042510',
 '042520',
 '042600',
 '042940',
 '043090',
 '043100',
 '043150',
 '043200',
 '043220',
 '043260',
 '043340',
 '043360',
 '043370',
 '043590',
 '043610',
 '043650',
 '043710',
 '043910',
 '044060',
 '044180',
 '044340',
 '044480',
 '044490',
 '044780',
 '044960',
 '045060',
 '045100',
 '045300',
 '045340',
 '045390',
 '045510',
 '045520',
 '045660',
 '045890',
 '045970',
 '046070',
 '046110',
 '046120',
 '046140',
 '046210',
 '046310',
 '046390',
 '046440',
 '046890',
 '046940',
 '046970',
 '047080',
 '047310',
 '047560',
 '047770',
 '047820',
 '047920',
 '048260',
 '048410',
 '048430',
 '048470',
 '048530',
 '048550',
 '048770',
 '048830',
 '048870',
 '048910',
 '049070',
 '049080',
 '049120',
 '049180',
 '049430',
 '049470',
 '049480',
 '049520',
 '049550',
 '049630',
 '049720',
 '049830',
 '049950',
 '049960',
 '050090',
 '050110',
 '050120',
 '050320',
 '050540',
 '050760',
 '050860',
 '050890',
 '050960',
 '051160',
 '051360',
 '051370',
 '051380',
 '051390',
 '051490',
 '051500',
 '051780',
 '051980',
 '052020',
 '052190',
 '052220',
 '052260',
 '052300',
 '052330',
 '052400',
 '052420',
 '052460',
 '052600',
 '052670',
 '052710',
 '052770',
 '052790',
 '052860',
 '052900',
 '053030',
 '053050',
 '053060',
 '053080',
 '053110',
 '053160',
 '053260',
 '053270',
 '053280',
 '053290',
 '053300',
 '053350',
 '053450',
 '053580',
 '053590',
 '053610',
 '053620',
 '053660',
 '053700',
 '053800',
 '053950',
 '053980',
 '054040',
 '054050',
 '054090',
 '054180',
 '054210',
 '054220',
 '054300',
 '054410',
 '054450',
 '054540',
 '054620',
 '054630',
 '054670',
 '054780',
 '054800',
 '054920',
 '054930',
 '054940',
 '054950',
 '056000',
 '056080',
 '056090',
 '056190',
 '056360',
 '056700',
 '056730',
 '057030',
 '057540',
 '057680',
 '057880',
 '058110',
 '058220',
 '058400',
 '058420',
 '058450',
 '058470',
 '058530',
 '058610',
 '058630',
 '058820',
 '058970',
 '059090',
 '059100',
 '059120',
 '059210',
 '059270',
 '060150',
 '060230',
 '060240',
 '060250',
 '060260',
 '060280',
 '060300',
 '060310',
 '060370',
 '060380',
 '060480',
 '060540',
 '060560',
 '060570',
 '060590',
 '060720',
 '060850',
 '060900',
 '061040',
 '061250',
 '061970',
 '062860',
 '062970',
 '063080',
 '063170',
 '063440',
 '063570',
 '063760',
 '064090',
 '064240',
 '064260',
 '064290',
 '064480',
 '064510',
 '064520',
 '064550',
 '064760',
 '064800',
 '064820',
 '064850',
 '065060',
 '065130',
 '065150',
 '065170',
 '065350',
 '065370',
 '065420',
 '065440',
 '065450',
 '065500',
 '065510',
 '065530',
 '065560',
 '065570',
 '065650',
 '065660',
 '065680',
 '065690',
 '065710',
 '065770',
 '065950',
 '066110',
 '066130',
 '066310',
 '066360',
 '066410',
 '066430',
 '066590',
 '066620',
 '066670',
 '066700',
 '066790',
 '066900',
 '066910',
 '066970',
 '066980',
 '067000',
 '067010',
 '067080',
 '067160',
 '067170',
 '067280',
 '067290',
 '067310',
 '067390',
 '067570',
 '067630',
 '067730',
 '067770',
 '067900',
 '067920',
 '067990',
 '068050',
 '068240',
 '068330',
 '068760',
 '068790',
 '068930',
 '068940',
 '069080',
 '069110',
 '069140',
 '069330',
 '069410',
 '069510',
 '069540',
 '069920',
 '070300',
 '070590',
 '071200',
 '071280',
 '071460',
 '071670',
 '071850',
 '072020',
 '072470',
 '072520',
 '072770',
 '072870',
 '072950',
 '072990',
 '073010',
 '073110',
 '073190',
 '073490',
 '073540',
 '073560',
 '073570',
 '073640',
 '074430',
 '074600',
 '075130',
 '075970',
 '076080',
 '076610',
 '077360',
 '078020',
 '078070',
 '078130',
 '078140',
 '078150',
 '078160',
 '078340',
 '078350',
 '078590',
 '078600',
 '078650',
 '078860',
 '078890',
 '078940',
 '079000',
 '079170',
 '079190',
 '079370',
 '079650',
 '079810',
 '079940',
 '079950',
 '079960',
 '079970',
 '080000',
 '080010',
 '080160',
 '080220',
 '080420',
 '080440',
 '080470',
 '080520',
 '080530',
 '080580',
 '080720',
 '081150',
 '081580',
 '082210',
 '082270',
 '082660',
 '082800',
 '082850',
 '082920',
 '083310',
 '083450',
 '083470',
 '083500',
 '083550',
 '083640',
 '083650',
 '083660',
 '083790',
 '083930',
 '084110',
 '084180',
 '084370',
 '084650',
 '084730',
 '084850',
 '084990',
 '085370',
 '08537M',
 '085660',
 '085670',
 '085810',
 '085910',
 '086040',
 '086060',
 '086250',
 '086390',
 '086450',
 '086520',
 '086670',
 '086710',
 '086820',
 '086890',
 '086900',
 '086960',
 '086980',
 '087010',
 '087260',
 '087600',
 '087730',
 '088130',
 '088290',
 '088390',
 '088800',
 '088910',
 '089010',
 '089030',
 '089140',
 '089150',
 '089230',
 '089530',
 '089600',
 '089790',
 '089850',
 '089890',
 '089970',
 '089980',
 '090150',
 '090360',
 '090410',
 '090460',
 '090470',
 '090710',
 '090740',
 '090850',
 '091120',
 '091340',
 '091440',
 '091580',
 '091590',
 '091700',
 '091970',
 '091990',
 '092040',
 '092070',
 '092130',
 '092190',
 '092300',
 '092460',
 '092600',
 '092730',
 '092870',
 '093190',
 '093320',
 '093380',
 '093520',
 '093640',
 '093920',
 '094170',
 '094360',
 '094480',
 '094820',
 '094840',
 '094850',
 '094860',
 '094940',
 '094970',
 '095190',
 '095270',
 '095340',
 '095500',
 '095610',
 '095660',
 '095700',
 '095910',
 '096040',
 '096240',
 '096350',
 '096530',
 '096610',
 '096630',
 '096640',
 '096690',
 '096870',
 '097780',
 '097800',
 '097870',
 '098120',
 '098460',
 '098660',
 '099190',
 '099220',
 '099320',
 '099410',
 '099440',
 '099520',
 '099750',
 '100030',
 '100090',
 '100120',
 '100130',
 '100590',
 '100660',
 '100700',
 '100790',
 '101000',
 '101160',
 '101170',
 '101240',
 '101330',
 '101360',
 '101390',
 '101400',
 '101490',
 '101670',
 '101680',
 '101730',
 '101930',
 '102120',
 '102710',
 '102940',
 '103230',
 '103840',
 '104040',
 '104200',
 '104460',
 '104480',
 '104540',
 '104620',
 '104830',
 '105330',
 '105550',
 '105740',
 '106080',
 '106190',
 '106240',
 '106520',
 '108230',
 '108320',
 '108380',
 '108490',
 '108860',
 '109080',
 '109610',
 '109740',
 '109820',
 '109860',
 '109960',
 '110020',
 '110790',
 '110990',
 '111710',
 '111820',
 '111870',
 '112040',
 '113810',
 '114120',
 '114190',
 '114450',
 '114570',
 '114630',
 '114810',
 '115160',
 '115180',
 '115310',
 '115440',
 '115450',
 '115480',
 '115500',
 '115530',
 '115570',
 '115610',
 '115960',
 '117670',
 '117730',
 '118990',
 '119500',
 '119610',
 '119830',
 '119850',
 '119860',
 '120240',
 '121440',
 '121600',
 '121800',
 '121850',
 '121890',
 '122310',
 '122350',
 '122450',
 '122640',
 '122690',
 '122870',
 '122990',
 '123010',
 '123040',
 '123330',
 '123410',
 '123420',
 '123570',
 '123750',
 '123840',
 '123860',
 '124500',
 '124560',
 '125210',
 '126340',
 '126600',
 '126640',
 '126700',
 '126870',
 '126880',
 '127120',
 '127160',
 '127710',
 '128540',
 '128660',
 '129890',
 '130500',
 '130580',
 '130740',
 '131030',
 '131090',
 '131100',
 '131180',
 '131220',
 '131290',
 '131370',
 '131390',
 '131400',
 '131760',
 '131970',
 '133750',
 '134060',
 '134580',
 '136480',
 '136510',
 '136540',
 '137400',
 '137940',
 '137950',
 '138070',
 '138080',
 '138360',
 '138580',
 '138610',
 '138690',
 '139050',
 '139670',
 '140070',
 '140410',
 '140520',
 '140670',
 '140860',
 '141000',
 '141020',
 '141070',
 '141080',
 '142210',
 '142280',
 '142760',
 '143160',
 '143240',
 '143540',
 '144510',
 '144960',
 '145020',
 '147760',
 '147830',
 '148140',
 '148150',
 '148250',
 '149950',
 '149980',
 '150840',
 '150900',
 '151860',
 '151910',
 '153460',
 '153490',
 '153710',
 '154030',
 '154040',
 '155650',
 '156100',
 ...]

In [ ]:
for idx, target_stock_code in enumerate(stock_code_list):
    if idx == 800:
        break
    print(str(idx) + '/' + str(len(stock_code_list)) + ' 현재 ' + str(target_stock_code) + '의 매매 데이터를 불러오는 중')
    kiwoom.calculator_list = []
    kiwoom.get_cummulative_buy_or_sale_of_investor_stockwise(stock_code=target_stock_code, start_date = target_start_date, end_date = target_end_date, price_or_volume = target_price_or_volume, net_or_buy_or_sale = target_net_or_buy_or_sale, unit_code = target_unit_code)
    raw_data = kiwoom.calculator_list[0]
    parsed_data = [int(rd.strip()) for rd in raw_data]
    stockwise_dict[target_stock_code] = parsed_data

0/1510 현재 900110의 매매 데이터를 불러오는 중
1/1510 현재 900270의 매매 데이터를 불러오는 중
2/1510 현재 900260의 매매 데이터를 불러오는 중
3/1510 현재 900290의 매매 데이터를 불러오는 중
4/1510 현재 900300의 매매 데이터를 불러오는 중
5/1510 현재 900310의 매매 데이터를 불러오는 중
6/1510 현재 900340의 매매 데이터를 불러오는 중
7/1510 현재 000250의 매매 데이터를 불러오는 중
8/1510 현재 000440의 매매 데이터를 불러오는 중
9/1510 현재 001000의 매매 데이터를 불러오는 중
10/1510 현재 001540의 매매 데이터를 불러오는 중
11/1510 현재 001810의 매매 데이터를 불러오는 중
12/1510 현재 001840의 매매 데이터를 불러오는 중
13/1510 현재 002230의 매매 데이터를 불러오는 중
14/1510 현재 002290의 매매 데이터를 불러오는 중
15/1510 현재 002680의 매매 데이터를 불러오는 중
16/1510 현재 002800의 매매 데이터를 불러오는 중
17/1510 현재 003100의 매매 데이터를 불러오는 중
18/1510 현재 003310의 매매 데이터를 불러오는 중
19/1510 현재 003380의 매매 데이터를 불러오는 중
20/1510 현재 003800의 매매 데이터를 불러오는 중
21/1510 현재 004590의 매매 데이터를 불러오는 중
22/1510 현재 004650의 매매 데이터를 불러오는 중
23/1510 현재 004780의 매매 데이터를 불러오는 중
24/1510 현재 005160의 매매 데이터를 불러오는 중
25/1510 현재 005290의 매매 데이터를 불러오는 중
26/1510 현재 005670의 매매 데이터를 불러오는 중
27/1510 현재 005710의 매매 데이터를 불러오는 중
28/1510 현재 005860의 매매 데이터를 불러오는 중
29/1510 현재 005990의 매매 데이터를 불러오는 중
30/1510 현재 006050의 매매 데이터를 불러오는 중
31/1510 현재 006140의 매매 데이터를 불러오는 중
32/1510 현재 006580의 매매 데이터를 불러오는 중
33/1510 현재 006620의 매매 데이터를 불러오는 중
34/1510 현재 006730의 매매 데이터를 불러오는 중
35/1510 현재 006910의 매매 데이터를 불러오는 중
36/1510 현재 006920의 매매 데이터를 불러오는 중
37/1510 현재 007330의 매매 데이터를 불러오는 중
38/1510 현재 007370의 매매 데이터를 불러오는 중
39/1510 현재 007390의 매매 데이터를 불러오는 중
40/1510 현재 007530의 매매 데이터를 불러오는 중
41/1510 현재 007680의 매매 데이터를 불러오는 중
42/1510 현재 007720의 매매 데이터를 불러오는 중
43/1510 현재 007770의 매매 데이터를 불러오는 중
44/1510 현재 007820의 매매 데이터를 불러오는 중
45/1510 현재 008290의 매매 데이터를 불러오는 중
46/1510 현재 008370의 매매 데이터를 불러오는 중
47/1510 현재 008470의 매매 데이터를 불러오는 중
48/1510 현재 008830의 매매 데이터를 불러오는 중
49/1510 현재 009300의 매매 데이터를 불러오는 중
50/1510 현재 009520의 매매 데이터를 불러오는 중
51/1510 현재 009620의 매매 데이터를 불러오는 중
52/1510 현재 009730의 매매 데이터를 불러오는 중
53/1510 현재 009780의 매매 데이터를 불러오는 중
54/1510 현재 010170의 매매 데이터를 불러오는 중
55/1510 현재 010240의 매매 데이터를 불러오는 중
56/1510 현재 010280의 매매 데이터를 불러오는 중
57/1510 현재 010470의 매매 데이터를 불러오는 중
58/1510 현재 011040의 매매 데이터를 불러오는 중
59/1510 현재 011080의 매매 데이터를 불러오는 중
60/1510 현재 011320의 매매 데이터를 불러오는 중
61/1510 현재 011370의 매매 데이터를 불러오는 중
62/1510 현재 011560의 매매 데이터를 불러오는 중
63/1510 현재 012340의 매매 데이터를 불러오는 중
64/1510 현재 012620의 매매 데이터를 불러오는 중
65/1510 현재 012700의 매매 데이터를 불러오는 중
66/1510 현재 012790의 매매 데이터를 불러오는 중
67/1510 현재 012860의 매매 데이터를 불러오는 중
68/1510 현재 013030의 매매 데이터를 불러오는 중
69/1510 현재 013120의 매매 데이터를 불러오는 중
70/1510 현재 013310의 매매 데이터를 불러오는 중
71/1510 현재 013720의 매매 데이터를 불러오는 중
72/1510 현재 013810의 매매 데이터를 불러오는 중
73/1510 현재 013990의 매매 데이터를 불러오는 중
74/1510 현재 014100의 매매 데이터를 불러오는 중
75/1510 현재 014190의 매매 데이터를 불러오는 중
76/1510 현재 014200의 매매 데이터를 불러오는 중
77/1510 현재 014470의 매매 데이터를 불러오는 중
78/1510 현재 014570의 매매 데이터를 불러오는 중
79/1510 현재 014620의 매매 데이터를 불러오는 중
80/1510 현재 014940의 매매 데이터를 불러오는 중
81/1510 현재 014970의 매매 데이터를 불러오는 중
82/1510 현재 015710의 매매 데이터를 불러오는 중
83/1510 현재 015750의 매매 데이터를 불러오는 중
84/1510 현재 016100의 매매 데이터를 불러오는 중
85/1510 현재 016250의 매매 데이터를 불러오는 중
86/1510 현재 016600의 매매 데이터를 불러오는 중
87/1510 현재 016670의 매매 데이터를 불러오는 중
88/1510 현재 016790의 매매 데이터를 불러오는 중
89/1510 현재 016920의 매매 데이터를 불러오는 중
90/1510 현재 017000의 매매 데이터를 불러오는 중
91/1510 현재 017250의 매매 데이터를 불러오는 중
92/1510 현재 017480의 매매 데이터를 불러오는 중
93/1510 현재 017510의 매매 데이터를 불러오는 중
94/1510 현재 017650의 매매 데이터를 불러오는 중
95/1510 현재 017890의 매매 데이터를 불러오는 중
96/1510 현재 018000의 매매 데이터를 불러오는 중
97/1510 현재 018120의 매매 데이터를 불러오는 중
98/1510 현재 018290의 매매 데이터를 불러오는 중
99/1510 현재 018310의 매매 데이터를 불러오는 중
100/1510 현재 018620의 매매 데이터를 불러오는 중
101/1510 현재 018680의 매매 데이터를 불러오는 중
102/1510 현재 018700의 매매 데이터를 불러오는 중
103/1510 현재 019010의 매매 데이터를 불러오는 중
104/1510 현재 019210의 매매 데이터를 불러오는 중
105/1510 현재 019540의 매매 데이터를 불러오는 중
106/1510 현재 019550의 매매 데이터를 불러오는 중
107/1510 현재 019570의 매매 데이터를 불러오는 중
108/1510 현재 019590의 매매 데이터를 불러오는 중
109/1510 현재 019660의 매매 데이터를 불러오는 중
110/1510 현재 019770의 매매 데이터를 불러오는 중
111/1510 현재 019990의 매매 데이터를 불러오는 중
112/1510 현재 020180의 매매 데이터를 불러오는 중
113/1510 현재 020400의 매매 데이터를 불러오는 중
114/1510 현재 020710의 매매 데이터를 불러오는 중
115/1510 현재 021040의 매매 데이터를 불러오는 중
116/1510 현재 021045의 매매 데이터를 불러오는 중
117/1510 현재 021080의 매매 데이터를 불러오는 중
118/1510 현재 021320의 매매 데이터를 불러오는 중
119/1510 현재 021650의 매매 데이터를 불러오는 중
120/1510 현재 021880의 매매 데이터를 불러오는 중
121/1510 현재 022100의 매매 데이터를 불러오는 중
122/1510 현재 022220의 매매 데이터를 불러오는 중
123/1510 현재 023160의 매매 데이터를 불러오는 중
124/1510 현재 023410의 매매 데이터를 불러오는 중
125/1510 현재 023440의 매매 데이터를 불러오는 중
126/1510 현재 023460의 매매 데이터를 불러오는 중
127/1510 현재 023600의 매매 데이터를 불러오는 중
128/1510 현재 023760의 매매 데이터를 불러오는 중
129/1510 현재 023770의 매매 데이터를 불러오는 중
130/1510 현재 023790의 매매 데이터를 불러오는 중
131/1510 현재 023900의 매매 데이터를 불러오는 중
132/1510 현재 023910의 매매 데이터를 불러오는 중
133/1510 현재 024060의 매매 데이터를 불러오는 중
134/1510 현재 024120의 매매 데이터를 불러오는 중
135/1510 현재 024740의 매매 데이터를 불러오는 중
136/1510 현재 024800의 매매 데이터를 불러오는 중
137/1510 현재 024810의 매매 데이터를 불러오는 중
138/1510 현재 024830의 매매 데이터를 불러오는 중
139/1510 현재 024840의 매매 데이터를 불러오는 중
140/1510 현재 024850의 매매 데이터를 불러오는 중
141/1510 현재 024880의 매매 데이터를 불러오는 중
142/1510 현재 024910의 매매 데이터를 불러오는 중
143/1510 현재 024940의 매매 데이터를 불러오는 중
144/1510 현재 024950의 매매 데이터를 불러오는 중
145/1510 현재 025320의 매매 데이터를 불러오는 중
146/1510 현재 025440의 매매 데이터를 불러오는 중
147/1510 현재 025550의 매매 데이터를 불러오는 중
148/1510 현재 025770의 매매 데이터를 불러오는 중
149/1510 현재 025870의 매매 데이터를 불러오는 중
150/1510 현재 025880의 매매 데이터를 불러오는 중
151/1510 현재 025900의 매매 데이터를 불러오는 중
152/1510 현재 025950의 매매 데이터를 불러오는 중
153/1510 현재 025980의 매매 데이터를 불러오는 중
154/1510 현재 026040의 매매 데이터를 불러오는 중
155/1510 현재 026150의 매매 데이터를 불러오는 중
156/1510 현재 026910의 매매 데이터를 불러오는 중
157/1510 현재 027040의 매매 데이터를 불러오는 중
158/1510 현재 027050의 매매 데이터를 불러오는 중
159/1510 현재 027360의 매매 데이터를 불러오는 중
160/1510 현재 027580의 매매 데이터를 불러오는 중
161/1510 현재 027710의 매매 데이터를 불러오는 중
162/1510 현재 027830의 매매 데이터를 불러오는 중
163/1510 현재 028080의 매매 데이터를 불러오는 중
164/1510 현재 028300의 매매 데이터를 불러오는 중
165/1510 현재 029480의 매매 데이터를 불러오는 중
166/1510 현재 029960의 매매 데이터를 불러오는 중
167/1510 현재 030190의 매매 데이터를 불러오는 중
168/1510 현재 030350의 매매 데이터를 불러오는 중
169/1510 현재 030520의 매매 데이터를 불러오는 중
170/1510 현재 030530의 매매 데이터를 불러오는 중
171/1510 현재 030960의 매매 데이터를 불러오는 중
172/1510 현재 031310의 매매 데이터를 불러오는 중
173/1510 현재 031330의 매매 데이터를 불러오는 중
174/1510 현재 031390의 매매 데이터를 불러오는 중
175/1510 현재 031510의 매매 데이터를 불러오는 중
176/1510 현재 031860의 매매 데이터를 불러오는 중
177/1510 현재 031980의 매매 데이터를 불러오는 중
178/1510 현재 032080의 매매 데이터를 불러오는 중
179/1510 현재 032190의 매매 데이터를 불러오는 중
180/1510 현재 032280의 매매 데이터를 불러오는 중
181/1510 현재 032300의 매매 데이터를 불러오는 중
182/1510 현재 032500의 매매 데이터를 불러오는 중
183/1510 현재 032540의 매매 데이터를 불러오는 중
184/1510 현재 032580의 매매 데이터를 불러오는 중
185/1510 현재 032620의 매매 데이터를 불러오는 중
186/1510 현재 032680의 매매 데이터를 불러오는 중
187/1510 현재 032685의 매매 데이터를 불러오는 중
188/1510 현재 032750의 매매 데이터를 불러오는 중
189/1510 현재 032790의 매매 데이터를 불러오는 중
190/1510 현재 032800의 매매 데이터를 불러오는 중
191/1510 현재 032820의 매매 데이터를 불러오는 중
192/1510 현재 032850의 매매 데이터를 불러오는 중
193/1510 현재 032860의 매매 데이터를 불러오는 중
194/1510 현재 032940의 매매 데이터를 불러오는 중
195/1510 현재 032960의 매매 데이터를 불러오는 중
196/1510 현재 032980의 매매 데이터를 불러오는 중
197/1510 현재 033050의 매매 데이터를 불러오는 중
198/1510 현재 033100의 매매 데이터를 불러오는 중
199/1510 현재 033110의 매매 데이터를 불러오는 중
200/1510 현재 033130의 매매 데이터를 불러오는 중
201/1510 현재 033160의 매매 데이터를 불러오는 중
202/1510 현재 033170의 매매 데이터를 불러오는 중
203/1510 현재 033200의 매매 데이터를 불러오는 중
204/1510 현재 033230의 매매 데이터를 불러오는 중
205/1510 현재 033290의 매매 데이터를 불러오는 중
206/1510 현재 033310의 매매 데이터를 불러오는 중
207/1510 현재 033320의 매매 데이터를 불러오는 중
208/1510 현재 033340의 매매 데이터를 불러오는 중
209/1510 현재 033430의 매매 데이터를 불러오는 중
210/1510 현재 033500의 매매 데이터를 불러오는 중
211/1510 현재 033540의 매매 데이터를 불러오는 중
212/1510 현재 033560의 매매 데이터를 불러오는 중
213/1510 현재 033600의 매매 데이터를 불러오는 중
214/1510 현재 033640의 매매 데이터를 불러오는 중
215/1510 현재 033790의 매매 데이터를 불러오는 중
216/1510 현재 033830의 매매 데이터를 불러오는 중
217/1510 현재 034230의 매매 데이터를 불러오는 중
218/1510 현재 034810의 매매 데이터를 불러오는 중
219/1510 현재 034940의 매매 데이터를 불러오는 중
220/1510 현재 034950의 매매 데이터를 불러오는 중
221/1510 현재 035080의 매매 데이터를 불러오는 중
222/1510 현재 035200의 매매 데이터를 불러오는 중
223/1510 현재 035290의 매매 데이터를 불러오는 중
224/1510 현재 035460의 매매 데이터를 불러오는 중
225/1510 현재 035600의 매매 데이터를 불러오는 중
226/1510 현재 035610의 매매 데이터를 불러오는 중
227/1510 현재 035620의 매매 데이터를 불러오는 중
228/1510 현재 035760의 매매 데이터를 불러오는 중
229/1510 현재 035810의 매매 데이터를 불러오는 중
230/1510 현재 035890의 매매 데이터를 불러오는 중
231/1510 현재 035900의 매매 데이터를 불러오는 중
232/1510 현재 036000의 매매 데이터를 불러오는 중
233/1510 현재 036010의 매매 데이터를 불러오는 중
234/1510 현재 036030의 매매 데이터를 불러오는 중
235/1510 현재 036090의 매매 데이터를 불러오는 중
236/1510 현재 036120의 매매 데이터를 불러오는 중
237/1510 현재 036170의 매매 데이터를 불러오는 중

238/1510 현재 036180의 매매 데이터를 불러오는 중
239/1510 현재 036190의 매매 데이터를 불러오는 중
240/1510 현재 036200의 매매 데이터를 불러오는 중
241/1510 현재 036480의 매매 데이터를 불러오는 중
242/1510 현재 036490의 매매 데이터를 불러오는 중
243/1510 현재 036540의 매매 데이터를 불러오는 중
244/1510 현재 036560의 매매 데이터를 불러오는 중
245/1510 현재 036620의 매매 데이터를 불러오는 중
246/1510 현재 036630의 매매 데이터를 불러오는 중
247/1510 현재 036640의 매매 데이터를 불러오는 중
248/1510 현재 036670의 매매 데이터를 불러오는 중
249/1510 현재 036690의 매매 데이터를 불러오는 중
250/1510 현재 036710의 매매 데이터를 불러오는 중
251/1510 현재 036800의 매매 데이터를 불러오는 중
252/1510 현재 036810의 매매 데이터를 불러오는 중
253/1510 현재 036830의 매매 데이터를 불러오는 중
254/1510 현재 036890의 매매 데이터를 불러오는 중
255/1510 현재 036930의 매매 데이터를 불러오는 중
256/1510 현재 037030의 매매 데이터를 불러오는 중
257/1510 현재 037070의 매매 데이터를 불러오는 중
258/1510 현재 037230의 매매 데이터를 불러오는 중
259/1510 현재 037330의 매매 데이터를 불러오는 중
260/1510 현재 037350의 매매 데이터를 불러오는 중
261/1510 현재 037370의 매매 데이터를 불러오는 중
262/1510 현재 037400의 매매 데이터를 불러오는 중
263/1510 현재 037440의 매매 데이터를 불러오는 중
264/1510 현재 037460의 매매 데이터를 불러오는 중
265/1510 현재 037760의 매매 데이터를 불러오는 중
266/1510 현재 037950의 매매 데이터를 불러오는 중
267/1510 현재 038010의 매매 데이터를 불러오는 중
268/1510 현재 038060의 매매 데이터를 불러오는 중
269/1510 현재 038070의 매매 데이터를 불러오는 중
270/1510 현재 038110의 매매 데이터를 불러오는 중
271/1510 현재 038160의 매매 데이터를 불러오는 중
272/1510 현재 038290의 매매 데이터를 불러오는 중
273/1510 현재 038340의 매매 데이터를 불러오는 중
274/1510 현재 038390의 매매 데이터를 불러오는 중
275/1510 현재 038460의 매매 데이터를 불러오는 중
276/1510 현재 038500의 매매 데이터를 불러오는 중
277/1510 현재 038530의 매매 데이터를 불러오는 중
278/1510 현재 038540의 매매 데이터를 불러오는 중
279/1510 현재 038620의 매매 데이터를 불러오는 중
280/1510 현재 038680의 매매 데이터를 불러오는 중
281/1510 현재 038870의 매매 데이터를 불러오는 중
282/1510 현재 038880의 매매 데이터를 불러오는 중
283/1510 현재 038950의 매매 데이터를 불러오는 중
284/1510 현재 039010의 매매 데이터를 불러오는 중
285/1510 현재 039020의 매매 데이터를 불러오는 중
286/1510 현재 039030의 매매 데이터를 불러오는 중
287/1510 현재 039200의 매매 데이터를 불러오는 중
288/1510 현재 039230의 매매 데이터를 불러오는 중
289/1510 현재 039240의 매매 데이터를 불러오는 중
290/1510 현재 039290의 매매 데이터를 불러오는 중
291/1510 현재 039310의 매매 데이터를 불러오는 중
292/1510 현재 039340의 매매 데이터를 불러오는 중
293/1510 현재 039420의 매매 데이터를 불러오는 중
294/1510 현재 039440의 매매 데이터를 불러오는 중
295/1510 현재 039560의 매매 데이터를 불러오는 중
296/1510 현재 039610의 매매 데이터를 불러오는 중
297/1510 현재 039670의 매매 데이터를 불러오는 중
298/1510 현재 039740의 매매 데이터를 불러오는 중
299/1510 현재 039830의 매매 데이터를 불러오는 중
300/1510 현재 039840의 매매 데이터를 불러오는 중
301/1510 현재 039860의 매매 데이터를 불러오는 중
302/1510 현재 039980의 매매 데이터를 불러오는 중
303/1510 현재 040160의 매매 데이터를 불러오는 중
304/1510 현재 040300의 매매 데이터를 불러오는 중
305/1510 현재 040350의 매매 데이터를 불러오는 중
306/1510 현재 040420의 매매 데이터를 불러오는 중
307/1510 현재 040610의 매매 데이터를 불러오는 중
308/1510 현재 040910의 매매 데이터를 불러오는 중
309/1510 현재 041020의 매매 데이터를 불러오는 중
310/1510 현재 041140의 매매 데이터를 불러오는 중
311/1510 현재 041190의 매매 데이터를 불러오는 중
312/1510 현재 041440의 매매 데이터를 불러오는 중
313/1510 현재 041460의 매매 데이터를 불러오는 중
314/1510 현재 041510의 매매 데이터를 불러오는 중
315/1510 현재 041520의 매매 데이터를 불러오는 중
316/1510 현재 041590의 매매 데이터를 불러오는 중
317/1510 현재 041830의 매매 데이터를 불러오는 중
318/1510 현재 041910의 매매 데이터를 불러오는 중
319/1510 현재 041920의 매매 데이터를 불러오는 중
320/1510 현재 041930의 매매 데이터를 불러오는 중
321/1510 현재 041960의 매매 데이터를 불러오는 중
322/1510 현재 042000의 매매 데이터를 불러오는 중
323/1510 현재 042040의 매매 데이터를 불러오는 중
324/1510 현재 042110의 매매 데이터를 불러오는 중
325/1510 현재 042370의 매매 데이터를 불러오는 중
326/1510 현재 042420의 매매 데이터를 불러오는 중
327/1510 현재 042500의 매매 데이터를 불러오는 중
328/1510 현재 042510의 매매 데이터를 불러오는 중
329/1510 현재 042520의 매매 데이터를 불러오는 중
330/1510 현재 042600의 매매 데이터를 불러오는 중
331/1510 현재 042940의 매매 데이터를 불러오는 중
332/1510 현재 043090의 매매 데이터를 불러오는 중
333/1510 현재 043100의 매매 데이터를 불러오는 중
334/1510 현재 043150의 매매 데이터를 불러오는 중
335/1510 현재 043200의 매매 데이터를 불러오는 중
336/1510 현재 043220의 매매 데이터를 불러오는 중
337/1510 현재 043260의 매매 데이터를 불러오는 중
338/1510 현재 043340의 매매 데이터를 불러오는 중
339/1510 현재 043360의 매매 데이터를 불러오는 중
340/1510 현재 043370의 매매 데이터를 불러오는 중
341/1510 현재 043590의 매매 데이터를 불러오는 중
342/1510 현재 043610의 매매 데이터를 불러오는 중
343/1510 현재 043650의 매매 데이터를 불러오는 중
344/1510 현재 043710의 매매 데이터를 불러오는 중
345/1510 현재 043910의 매매 데이터를 불러오는 중
346/1510 현재 044060의 매매 데이터를 불러오는 중
347/1510 현재 044180의 매매 데이터를 불러오는 중
348/1510 현재 044340의 매매 데이터를 불러오는 중
349/1510 현재 044480의 매매 데이터를 불러오는 중
350/1510 현재 044490의 매매 데이터를 불러오는 중
351/1510 현재 044780의 매매 데이터를 불러오는 중
352/1510 현재 044960의 매매 데이터를 불러오는 중
353/1510 현재 045060의 매매 데이터를 불러오는 중
354/1510 현재 045100의 매매 데이터를 불러오는 중
355/1510 현재 045300의 매매 데이터를 불러오는 중
356/1510 현재 045340의 매매 데이터를 불러오는 중
357/1510 현재 045390의 매매 데이터를 불러오는 중
358/1510 현재 045510의 매매 데이터를 불러오는 중
359/1510 현재 045520의 매매 데이터를 불러오는 중
360/1510 현재 045660의 매매 데이터를 불러오는 중
361/1510 현재 045890의 매매 데이터를 불러오는 중
362/1510 현재 045970의 매매 데이터를 불러오는 중
363/1510 현재 046070의 매매 데이터를 불러오는 중
364/1510 현재 046110의 매매 데이터를 불러오는 중
365/1510 현재 046120의 매매 데이터를 불러오는 중
366/1510 현재 046140의 매매 데이터를 불러오는 중
367/1510 현재 046210의 매매 데이터를 불러오는 중
368/1510 현재 046310의 매매 데이터를 불러오는 중
369/1510 현재 046390의 매매 데이터를 불러오는 중
370/1510 현재 046440의 매매 데이터를 불러오는 중
371/1510 현재 046890의 매매 데이터를 불러오는 중
372/1510 현재 046940의 매매 데이터를 불러오는 중
373/1510 현재 046970의 매매 데이터를 불러오는 중
374/1510 현재 047080의 매매 데이터를 불러오는 중
375/1510 현재 047310의 매매 데이터를 불러오는 중
376/1510 현재 047560의 매매 데이터를 불러오는 중
377/1510 현재 047770의 매매 데이터를 불러오는 중
378/1510 현재 047820의 매매 데이터를 불러오는 중
379/1510 현재 047920의 매매 데이터를 불러오는 중
380/1510 현재 048260의 매매 데이터를 불러오는 중
381/1510 현재 048410의 매매 데이터를 불러오는 중
382/1510 현재 048430의 매매 데이터를 불러오는 중
383/1510 현재 048470의 매매 데이터를 불러오는 중
384/1510 현재 048530의 매매 데이터를 불러오는 중
385/1510 현재 048550의 매매 데이터를 불러오는 중
386/1510 현재 048770의 매매 데이터를 불러오는 중
387/1510 현재 048830의 매매 데이터를 불러오는 중
388/1510 현재 048870의 매매 데이터를 불러오는 중
389/1510 현재 048910의 매매 데이터를 불러오는 중
390/1510 현재 049070의 매매 데이터를 불러오는 중
391/1510 현재 049080의 매매 데이터를 불러오는 중
392/1510 현재 049120의 매매 데이터를 불러오는 중
393/1510 현재 049180의 매매 데이터를 불러오는 중
394/1510 현재 049430의 매매 데이터를 불러오는 중
395/1510 현재 049470의 매매 데이터를 불러오는 중
396/1510 현재 049480의 매매 데이터를 불러오는 중
397/1510 현재 049520의 매매 데이터를 불러오는 중
398/1510 현재 049550의 매매 데이터를 불러오는 중
399/1510 현재 049630의 매매 데이터를 불러오는 중
400/1510 현재 049720의 매매 데이터를 불러오는 중
401/1510 현재 049830의 매매 데이터를 불러오는 중
402/1510 현재 049950의 매매 데이터를 불러오는 중
403/1510 현재 049960의 매매 데이터를 불러오는 중
404/1510 현재 050090의 매매 데이터를 불러오는 중
405/1510 현재 050110의 매매 데이터를 불러오는 중
406/1510 현재 050120의 매매 데이터를 불러오는 중
407/1510 현재 050320의 매매 데이터를 불러오는 중
408/1510 현재 050540의 매매 데이터를 불러오는 중
409/1510 현재 050760의 매매 데이터를 불러오는 중
410/1510 현재 050860의 매매 데이터를 불러오는 중
411/1510 현재 050890의 매매 데이터를 불러오는 중
412/1510 현재 050960의 매매 데이터를 불러오는 중
413/1510 현재 051160의 매매 데이터를 불러오는 중
414/1510 현재 051360의 매매 데이터를 불러오는 중
415/1510 현재 051370의 매매 데이터를 불러오는 중
416/1510 현재 051380의 매매 데이터를 불러오는 중
417/1510 현재 051390의 매매 데이터를 불러오는 중
418/1510 현재 051490의 매매 데이터를 불러오는 중
419/1510 현재 051500의 매매 데이터를 불러오는 중
420/1510 현재 051780의 매매 데이터를 불러오는 중
421/1510 현재 051980의 매매 데이터를 불러오는 중
422/1510 현재 052020의 매매 데이터를 불러오는 중
423/1510 현재 052190의 매매 데이터를 불러오는 중
424/1510 현재 052220의 매매 데이터를 불러오는 중
425/1510 현재 052260의 매매 데이터를 불러오는 중
426/1510 현재 052300의 매매 데이터를 불러오는 중
427/1510 현재 052330의 매매 데이터를 불러오는 중
428/1510 현재 052400의 매매 데이터를 불러오는 중
429/1510 현재 052420의 매매 데이터를 불러오는 중
430/1510 현재 052460의 매매 데이터를 불러오는 중
431/1510 현재 052600의 매매 데이터를 불러오는 중
432/1510 현재 052670의 매매 데이터를 불러오는 중
433/1510 현재 052710의 매매 데이터를 불러오는 중
434/1510 현재 052770의 매매 데이터를 불러오는 중
435/1510 현재 052790의 매매 데이터를 불러오는 중
436/1510 현재 052860의 매매 데이터를 불러오는 중
437/1510 현재 052900의 매매 데이터를 불러오는 중
438/1510 현재 053030의 매매 데이터를 불러오는 중
439/1510 현재 053050의 매매 데이터를 불러오는 중
440/1510 현재 053060의 매매 데이터를 불러오는 중
441/1510 현재 053080의 매매 데이터를 불러오는 중
442/1510 현재 053110의 매매 데이터를 불러오는 중
443/1510 현재 053160의 매매 데이터를 불러오는 중
444/1510 현재 053260의 매매 데이터를 불러오는 중
445/1510 현재 053270의 매매 데이터를 불러오는 중
446/1510 현재 053280의 매매 데이터를 불러오는 중
447/1510 현재 053290의 매매 데이터를 불러오는 중
448/1510 현재 053300의 매매 데이터를 불러오는 중
449/1510 현재 053350의 매매 데이터를 불러오는 중
450/1510 현재 053450의 매매 데이터를 불러오는 중
451/1510 현재 053580의 매매 데이터를 불러오는 중
452/1510 현재 053590의 매매 데이터를 불러오는 중
453/1510 현재 053610의 매매 데이터를 불러오는 중
454/1510 현재 053620의 매매 데이터를 불러오는 중
455/1510 현재 053660의 매매 데이터를 불러오는 중
456/1510 현재 053700의 매매 데이터를 불러오는 중
457/1510 현재 053800의 매매 데이터를 불러오는 중
458/1510 현재 053950의 매매 데이터를 불러오는 중
459/1510 현재 053980의 매매 데이터를 불러오는 중
460/1510 현재 054040의 매매 데이터를 불러오는 중
461/1510 현재 054050의 매매 데이터를 불러오는 중
462/1510 현재 054090의 매매 데이터를 불러오는 중
463/1510 현재 054180의 매매 데이터를 불러오는 중
464/1510 현재 054210의 매매 데이터를 불러오는 중
465/1510 현재 054220의 매매 데이터를 불러오는 중
466/1510 현재 054300의 매매 데이터를 불러오는 중
467/1510 현재 054410의 매매 데이터를 불러오는 중
468/1510 현재 054450의 매매 데이터를 불러오는 중
469/1510 현재 054540의 매매 데이터를 불러오는 중
470/1510 현재 054620의 매매 데이터를 불러오는 중
471/1510 현재 054630의 매매 데이터를 불러오는 중
472/1510 현재 054670의 매매 데이터를 불러오는 중

473/1510 현재 054780의 매매 데이터를 불러오는 중
474/1510 현재 054800의 매매 데이터를 불러오는 중
475/1510 현재 054920의 매매 데이터를 불러오는 중
476/1510 현재 054930의 매매 데이터를 불러오는 중
477/1510 현재 054940의 매매 데이터를 불러오는 중
478/1510 현재 054950의 매매 데이터를 불러오는 중
479/1510 현재 056000의 매매 데이터를 불러오는 중
480/1510 현재 056080의 매매 데이터를 불러오는 중
481/1510 현재 056090의 매매 데이터를 불러오는 중
482/1510 현재 056190의 매매 데이터를 불러오는 중
483/1510 현재 056360의 매매 데이터를 불러오는 중
484/1510 현재 056700의 매매 데이터를 불러오는 중
485/1510 현재 056730의 매매 데이터를 불러오는 중
486/1510 현재 057030의 매매 데이터를 불러오는 중
487/1510 현재 057540의 매매 데이터를 불러오는 중
488/1510 현재 057680의 매매 데이터를 불러오는 중
489/1510 현재 057880의 매매 데이터를 불러오는 중
490/1510 현재 058110의 매매 데이터를 불러오는 중
491/1510 현재 058220의 매매 데이터를 불러오는 중
492/1510 현재 058400의 매매 데이터를 불러오는 중
493/1510 현재 058420의 매매 데이터를 불러오는 중
494/1510 현재 058450의 매매 데이터를 불러오는 중
495/1510 현재 058470의 매매 데이터를 불러오는 중
496/1510 현재 058530의 매매 데이터를 불러오는 중
497/1510 현재 058610의 매매 데이터를 불러오는 중
498/1510 현재 058630의 매매 데이터를 불러오는 중
499/1510 현재 058820의 매매 데이터를 불러오는 중
500/1510 현재 058970의 매매 데이터를 불러오는 중
501/1510 현재 059090의 매매 데이터를 불러오는 중
502/1510 현재 059100의 매매 데이터를 불러오는 중
503/1510 현재 059120의 매매 데이터를 불러오는 중
504/1510 현재 059210의 매매 데이터를 불러오는 중
505/1510 현재 059270의 매매 데이터를 불러오는 중
506/1510 현재 060150의 매매 데이터를 불러오는 중
507/1510 현재 060230의 매매 데이터를 불러오는 중
508/1510 현재 060240의 매매 데이터를 불러오는 중
509/1510 현재 060250의 매매 데이터를 불러오는 중
510/1510 현재 060260의 매매 데이터를 불러오는 중
511/1510 현재 060280의 매매 데이터를 불러오는 중
512/1510 현재 060300의 매매 데이터를 불러오는 중
513/1510 현재 060310의 매매 데이터를 불러오는 중
514/1510 현재 060370의 매매 데이터를 불러오는 중
515/1510 현재 060380의 매매 데이터를 불러오는 중
516/1510 현재 060480의 매매 데이터를 불러오는 중
517/1510 현재 060540의 매매 데이터를 불러오는 중
518/1510 현재 060560의 매매 데이터를 불러오는 중
519/1510 현재 060570의 매매 데이터를 불러오는 중
520/1510 현재 060590의 매매 데이터를 불러오는 중
521/1510 현재 060720의 매매 데이터를 불러오는 중
522/1510 현재 060850의 매매 데이터를 불러오는 중
523/1510 현재 060900의 매매 데이터를 불러오는 중
524/1510 현재 061040의 매매 데이터를 불러오는 중
525/1510 현재 061250의 매매 데이터를 불러오는 중
526/1510 현재 061970의 매매 데이터를 불러오는 중
527/1510 현재 062860의 매매 데이터를 불러오는 중
528/1510 현재 062970의 매매 데이터를 불러오는 중
529/1510 현재 063080의 매매 데이터를 불러오는 중
530/1510 현재 063170의 매매 데이터를 불러오는 중
531/1510 현재 063440의 매매 데이터를 불러오는 중
532/1510 현재 063570의 매매 데이터를 불러오는 중
533/1510 현재 063760의 매매 데이터를 불러오는 중
534/1510 현재 064090의 매매 데이터를 불러오는 중
535/1510 현재 064240의 매매 데이터를 불러오는 중
536/1510 현재 064260의 매매 데이터를 불러오는 중
537/1510 현재 064290의 매매 데이터를 불러오는 중
538/1510 현재 064480의 매매 데이터를 불러오는 중
539/1510 현재 064510의 매매 데이터를 불러오는 중
540/1510 현재 064520의 매매 데이터를 불러오는 중
541/1510 현재 064550의 매매 데이터를 불러오는 중
542/1510 현재 064760의 매매 데이터를 불러오는 중
543/1510 현재 064800의 매매 데이터를 불러오는 중
544/1510 현재 064820의 매매 데이터를 불러오는 중
545/1510 현재 064850의 매매 데이터를 불러오는 중
546/1510 현재 065060의 매매 데이터를 불러오는 중
547/1510 현재 065130의 매매 데이터를 불러오는 중
548/1510 현재 065150의 매매 데이터를 불러오는 중
549/1510 현재 065170의 매매 데이터를 불러오는 중
550/1510 현재 065350의 매매 데이터를 불러오는 중
551/1510 현재 065370의 매매 데이터를 불러오는 중
552/1510 현재 065420의 매매 데이터를 불러오는 중
553/1510 현재 065440의 매매 데이터를 불러오는 중
554/1510 현재 065450의 매매 데이터를 불러오는 중
555/1510 현재 065500의 매매 데이터를 불러오는 중
556/1510 현재 065510의 매매 데이터를 불러오는 중
557/1510 현재 065530의 매매 데이터를 불러오는 중
558/1510 현재 065560의 매매 데이터를 불러오는 중
559/1510 현재 065570의 매매 데이터를 불러오는 중
560/1510 현재 065650의 매매 데이터를 불러오는 중
561/1510 현재 065660의 매매 데이터를 불러오는 중
562/1510 현재 065680의 매매 데이터를 불러오는 중
563/1510 현재 065690의 매매 데이터를 불러오는 중
564/1510 현재 065710의 매매 데이터를 불러오는 중
565/1510 현재 065770의 매매 데이터를 불러오는 중
566/1510 현재 065950의 매매 데이터를 불러오는 중
567/1510 현재 066110의 매매 데이터를 불러오는 중
568/1510 현재 066130의 매매 데이터를 불러오는 중
569/1510 현재 066310의 매매 데이터를 불러오는 중
570/1510 현재 066360의 매매 데이터를 불러오는 중
571/1510 현재 066410의 매매 데이터를 불러오는 중
572/1510 현재 066430의 매매 데이터를 불러오는 중
573/1510 현재 066590의 매매 데이터를 불러오는 중
574/1510 현재 066620의 매매 데이터를 불러오는 중
575/1510 현재 066670의 매매 데이터를 불러오는 중
576/1510 현재 066700의 매매 데이터를 불러오는 중
577/1510 현재 066790의 매매 데이터를 불러오는 중
578/1510 현재 066900의 매매 데이터를 불러오는 중
579/1510 현재 066910의 매매 데이터를 불러오는 중
580/1510 현재 066970의 매매 데이터를 불러오는 중
581/1510 현재 066980의 매매 데이터를 불러오는 중
582/1510 현재 067000의 매매 데이터를 불러오는 중
583/1510 현재 067010의 매매 데이터를 불러오는 중
584/1510 현재 067080의 매매 데이터를 불러오는 중
585/1510 현재 067160의 매매 데이터를 불러오는 중
586/1510 현재 067170의 매매 데이터를 불러오는 중
587/1510 현재 067280의 매매 데이터를 불러오는 중
588/1510 현재 067290의 매매 데이터를 불러오는 중
589/1510 현재 067310의 매매 데이터를 불러오는 중
590/1510 현재 067390의 매매 데이터를 불러오는 중
591/1510 현재 067570의 매매 데이터를 불러오는 중
592/1510 현재 067630의 매매 데이터를 불러오는 중
593/1510 현재 067730의 매매 데이터를 불러오는 중
594/1510 현재 067770의 매매 데이터를 불러오는 중
595/1510 현재 067900의 매매 데이터를 불러오는 중
596/1510 현재 067920의 매매 데이터를 불러오는 중
597/1510 현재 067990의 매매 데이터를 불러오는 중
598/1510 현재 068050의 매매 데이터를 불러오는 중
599/1510 현재 068240의 매매 데이터를 불러오는 중
600/1510 현재 068330의 매매 데이터를 불러오는 중
601/1510 현재 068760의 매매 데이터를 불러오는 중
602/1510 현재 068790의 매매 데이터를 불러오는 중
603/1510 현재 068930의 매매 데이터를 불러오는 중
604/1510 현재 068940의 매매 데이터를 불러오는 중
605/1510 현재 069080의 매매 데이터를 불러오는 중
606/1510 현재 069110의 매매 데이터를 불러오는 중
607/1510 현재 069140의 매매 데이터를 불러오는 중
608/1510 현재 069330의 매매 데이터를 불러오는 중
609/1510 현재 069410의 매매 데이터를 불러오는 중
610/1510 현재 069510의 매매 데이터를 불러오는 중
611/1510 현재 069540의 매매 데이터를 불러오는 중
612/1510 현재 069920의 매매 데이터를 불러오는 중
613/1510 현재 070300의 매매 데이터를 불러오는 중
614/1510 현재 070590의 매매 데이터를 불러오는 중
615/1510 현재 071200의 매매 데이터를 불러오는 중
616/1510 현재 071280의 매매 데이터를 불러오는 중
617/1510 현재 071460의 매매 데이터를 불러오는 중
618/1510 현재 071670의 매매 데이터를 불러오는 중
619/1510 현재 071850의 매매 데이터를 불러오는 중
620/1510 현재 072020의 매매 데이터를 불러오는 중
621/1510 현재 072470의 매매 데이터를 불러오는 중
622/1510 현재 072520의 매매 데이터를 불러오는 중
623/1510 현재 072770의 매매 데이터를 불러오는 중
624/1510 현재 072870의 매매 데이터를 불러오는 중
625/1510 현재 072950의 매매 데이터를 불러오는 중
626/1510 현재 072990의 매매 데이터를 불러오는 중
627/1510 현재 073010의 매매 데이터를 불러오는 중
628/1510 현재 073110의 매매 데이터를 불러오는 중
629/1510 현재 073190의 매매 데이터를 불러오는 중
630/1510 현재 073490의 매매 데이터를 불러오는 중

In [ ]:
import pickle

In [ ]:
with open('stockwise_dict_20210709.pickle', 'wb') as f:
    pickle.dump(stockwise_dict, f)

In [ ]:
with open('stockwise_dict_20210709.pickle', 'rb') as fr:
    stockwise_dict = pickle.load(fr)

In [ ]:
for idx, target_stock_code in enumerate(stock_code_list):
    if idx < 800:
        continue
    print(str(idx) + '/' + str(len(stock_code_list)) + ' 현재 ' + str(target_stock_code) + '의 매매 데이터를 불러오는 중')
    kiwoom.calculator_list = []
    kiwoom.get_cummulative_buy_or_sale_of_investor_stockwise(stock_code=target_stock_code, start_date = target_start_date, end_date = target_end_date, price_or_volume = target_price_or_volume, net_or_buy_or_sale = target_net_or_buy_or_sale, unit_code = target_unit_code)
    raw_data = kiwoom.calculator_list[0]
    parsed_data = [int(rd.strip()) for rd in raw_data]
    stockwise_dict[target_stock_code] = parsed_data

In [ ]:
stockwise_dict

In [ ]:
with open('stockwise_dict_20210709.pickle', 'wb') as f:
    pickle.dump(stockwise_dict, f)

In [34]:
pension_fund_df = pd.DataFrame(columns=stock_code_list, index=['pension_fund_net'])

for idx, stock_code in enumerate(stock_code_list):
    pension_fund_df[stock_code] = [stockwise_dict[stock_code][8]]

In [35]:
pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0,0,0,0,0,0,0,-9479,0,0,...,-681,237,0,515,0,0,0,0,0,0

In [36]:
institution_df = pd.DataFrame(columns=stock_code_list, index=['institution_net'])

for idx, stock_code in enumerate(stock_code_list):
    institution_df[stock_code] = [stockwise_dict[stock_code][2]]

In [37]:
institution_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
institution_net,0,0,0,0,-19,20,0,-6951,-26,0,...,-2695,3490,0,-2264,7,0,0,0,50,0

In [38]:
closeprice_shareoutstanding_df = pd.DataFrame(columns = stock_code_list, index = ['closeprice', 'shareoutstanding']) 
for idx, stock_code in enumerate(stock_code_list):
    stockwise_result_list = []
    stockwise_result_list.append(int(kiwoom.dynamicCall("GetMasterLastPrice(QString)", stock_code)))
    stockwise_result_list.append(int(kiwoom.dynamicCall("GetMasterListedStockCnt(QString)", stock_code)))
    closeprice_shareoutstanding_df[stock_code] = stockwise_result_list

In [39]:
closeprice_shareoutstanding_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
closeprice,197,591,339,951,798,1870,1490,57600,15600,3040,...,28150,9200,8010,10400,12800,439,293,1450,1040,3585
shareoutstanding,136637536,80000000,180156443,67375000,64411060,54000000,47973428,22768041,6227130,24277540,...,36315527,19867866,61117550,98392010,18963553,176573591,116745963,67783852,53743968,30597535

In [40]:
pension_fund_df = pension_fund_df[stock_code_list]
institution_df = institution_df[stock_code_list]

In [41]:
pension_fund_df.to_csv("pension_fund_df.csv")
institution_df.to_csv("institution_df.csv")

In [42]:
pension_fund_df = pd.read_csv("pension_fund_df.csv", index_col=0)
institution_df = pd.read_csv("institution_df.csv", index_col=0)

In [43]:
pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0,0,0,0,0,0,0,-9479,0,0,...,-681,237,0,515,0,0,0,0,0,0

In [44]:
institution_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
institution_net,0,0,0,0,-19,20,0,-6951,-26,0,...,-2695,3490,0,-2264,7,0,0,0,50,0

In [45]:
closeprice_shareoutstanding_df.to_csv("closeprice_shareoutstanding_df.csv", index=True)

In [46]:
closeprice_shareoutstanding_df = pd.read_csv("closeprice_shareoutstanding_df.csv", index_col=0)

In [47]:
closeprice_shareoutstanding_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
closeprice,197,591,339,951,798,1870,1490,57600,15600,3040,...,28150,9200,8010,10400,12800,439,293,1450,1040,3585
shareoutstanding,136637536,80000000,180156443,67375000,64411060,54000000,47973428,22768041,6227130,24277540,...,36315527,19867866,61117550,98392010,18963553,176573591,116745963,67783852,53743968,30597535

In [48]:
total_pension_fund_df= pd.concat([pension_fund_df, closeprice_shareoutstanding_df])

In [49]:
total_pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0,0,0,0,0,0,0,-9479,0,0,...,-681,237,0,515,0,0,0,0,0,0
closeprice,197,591,339,951,798,1870,1490,57600,15600,3040,...,28150,9200,8010,10400,12800,439,293,1450,1040,3585
shareoutstanding,136637536,80000000,180156443,67375000,64411060,54000000,47973428,22768041,6227130,24277540,...,36315527,19867866,61117550,98392010,18963553,176573591,116745963,67783852,53743968,30597535

In [50]:
total_pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0,0,0,0,0,0,0,-9479,0,0,...,-681,237,0,515,0,0,0,0,0,0
closeprice,197,591,339,951,798,1870,1490,57600,15600,3040,...,28150,9200,8010,10400,12800,439,293,1450,1040,3585
shareoutstanding,136637536,80000000,180156443,67375000,64411060,54000000,47973428,22768041,6227130,24277540,...,36315527,19867866,61117550,98392010,18963553,176573591,116745963,67783852,53743968,30597535

In [53]:
total_pension_fund_df.loc['pension_fund_net_mil']= total_pension_fund_df.loc['pension_fund_net']*1000000

In [55]:
total_pension_fund_df.loc['market_cap']= total_pension_fund_df.loc['closeprice']*total_pension_fund_df.loc['shareoutstanding']

In [56]:
total_pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0,0,0,0,0,0,0,-9479,0,0,...,-681,237,0,515,0,0,0,0,0,0
closeprice,197,591,339,951,798,1870,1490,57600,15600,3040,...,28150,9200,8010,10400,12800,439,293,1450,1040,3585
shareoutstanding,136637536,80000000,180156443,67375000,64411060,54000000,47973428,22768041,6227130,24277540,...,36315527,19867866,61117550,98392010,18963553,176573591,116745963,67783852,53743968,30597535
pension_fund_net_mil,0,0,0,0,0,0,0,-9479000000,0,0,...,-681000000,237000000,0,515000000,0,0,0,0,0,0
market_cap,26917594592,47280000000,61073034177,64073625000,51400025880,100980000000,71480407720,1311439161600,97143228000,73803721600,...,1022282085050,182784367200,489551575500,1023276904000,242733478400,77515806449,34206567159,98286585400,55893726720,109692162975

In [57]:
total_pension_fund_df.loc['pension_portion']=total_pension_fund_df.loc['pension_fund_net_mil']/total_pension_fund_df.loc['market_cap']

In [58]:
total_pension_fund_df

,900110,900270,900260,900290,900300,900310,900340,000250,000440,001000,...,950130,950140,950160,950220,950200,900280,900120,900250,900070,900100
pension_fund_net,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.479000e+03,0.000000e+00,0.000000e+00,...,-6.810000e+02,2.370000e+02,0.000000e+00,5.150000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
closeprice,1.970000e+02,5.910000e+02,3.390000e+02,9.510000e+02,7.980000e+02,1.870000e+03,1.490000e+03,5.760000e+04,1.560000e+04,3.040000e+03,...,2.815000e+04,9.200000e+03,8.010000e+03,1.040000e+04,1.280000e+04,4.390000e+02,2.930000e+02,1.450000e+03,1.040000e+03,3.585000e+03
shareoutstanding,1.366375e+08,8.000000e+07,1.801564e+08,6.737500e+07,6.441106e+07,5.400000e+07,4.797343e+07,2.276804e+07,6.227130e+06,2.427754e+07,...,3.631553e+07,1.986787e+07,6.111755e+07,9.839201e+07,1.896355e+07,1.765736e+08,1.167460e+08,6.778385e+07,5.374397e+07,3.059754e+07
pension_fund_net_mil,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.479000e+09,0.000000e+00,0.000000e+00,...,-6.810000e+08,2.370000e+08,0.000000e+00,5.150000e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
market_cap,2.691759e+10,4.728000e+10,6.107303e+10,6.407362e+10,5.140003e+10,1.009800e+11,7.148041e+10,1.311439e+12,9.714323e+10,7.380372e+10,...,1.022282e+12,1.827844e+11,4.895516e+11,1.023277e+12,2.427335e+11,7.751581e+10,3.420657e+10,9.828659e+10,5.589373e+10,1.096922e+11
pension_portion,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.227937e-03,0.000000e+00,0.000000e+00,...,-6.661566e-04,1.296610e-03,0.000000e+00,5.032851e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [67]:
pension_portion_df = total_pension_fund_df.transpose()[['pension_portion']]

In [68]:
pension_portion_df

        pension_portion
900110              0.0
900270              0.0
900260              0.0
900290              0.0
900300              0.0
...                 ...
900280              0.0
900120              0.0
900250              0.0
900070              0.0
900100              0.0

[1509 rows x 1 columns]

In [70]:
rank_pension_portion_df= pension_portion_df.sort_values(by='pension_portion', ascending=False)

In [74]:
rank_stock_code_list = list(rank_pension_portion_df.index)

In [77]:
rank_stock_name_list = [kiwoom.dynamicCall("GetMasterCodeName(QString)", code) for code in rank_stock_code_list]

In [79]:
rank_pension_portion_df['stock_name']=rank_stock_name_list

In [83]:
rank_pension_portion_df.head(50)

        pension_portion stock_name
298540         0.024426    더네이쳐홀딩스
119610         0.023564       인터로조
317330         0.017879     덕산테코피아
014620         0.017516       성광벤드
023160         0.017092         태광
222800         0.015310         심텍
042000         0.014597       카페24
272290         0.014156    이녹스첨단소재
086520         0.012967       에코프로
064290         0.012260      인텍플러스
084650         0.011980      랩지노믹스
237690         0.011514       에스티팜
214450         0.010583      파마리서치
096240         0.010499       청담러닝
036200         0.010183        유니셈
278280         0.009854         천보
137950         0.009353     제이씨케미칼
110790         0.009243    크리스에프앤씨
131970         0.007926        테스나
101160         0.007782        월덱스
126340         0.007561        비나텍
270870         0.007510        뉴트리
294570         0.007109         쿠콘
131390         0.006929      원익피앤이
063170         0.006501       서울옥션
228670         0.006390         레이
051160         0.006048      지어소프트
287410         0.005927    제이시스메디칼
084370         0.005832       유진테크
121600         0.005811      나노신소재
160550         0.005570        NEW
131290         0.005425       티에스이
235980         0.005419       메드팩토
065350         0.005266     신성델타테크
051370         0.005144      인터플렉스
356860         0.004966        티엘비
088800         0.004760      에이스테크
064260         0.004675         다날
290670         0.004614     대보마그네틱
025900         0.004613       동화기업
318020         0.004439     포인트모바일
213420         0.004411     덕산네오룩스
194700         0.004405       노바렉스
079940         0.004352        가비아
036830         0.004283    솔브레인홀딩스
065680         0.003835     우주일렉트로
238200         0.003639        비피도
101490         0.003516     에스앤에스텍
222040         0.003487    코스맥스엔비티
079370         0.003476        제우스

In [84]:
pension_amount_df = total_pension_fund_df.transpose()[['pension_fund_net_mil']]

In [85]:
rank_pension_amount_df = pension_amount_df.sort_values(by='pension_fund_net_mil', ascending=False)

In [86]:
rank_stock_code_list = list(rank_pension_amount_df.index)

In [87]:
rank_stock_name_list = [kiwoom.dynamicCall("GetMasterCodeName(QString)", code) for code in rank_stock_code_list]

In [88]:
rank_pension_amount_df['stock_name']=rank_stock_name_list

In [89]:
rank_pension_amount_df.head(50)

        pension_fund_net_mil stock_name
086520          2.449200e+10       에코프로
237690          2.425100e+10       에스티팜
278280          2.325500e+10         천보
222800          1.499600e+10         심텍
263750          1.313900e+10       펄어비스
042000          1.226200e+10       카페24
066970          1.164500e+10       엘앤에프
272290          1.105200e+10    이녹스첨단소재
214450          1.014500e+10      파마리서치
317330          9.167000e+09     덕산테코피아
119610          8.292000e+09       인터로조
213420          7.435000e+09     덕산네오룩스
025900          7.417000e+09       동화기업
235980          7.046000e+09       메드팩토
131970          6.329000e+09        테스나
084370          6.235000e+09       유진테크
298540          5.933000e+09    더네이쳐홀딩스
023160          5.775000e+09         태광
035900          4.893000e+09   JYP Ent.
131290          4.753000e+09       티에스이
014620          4.699000e+09       성광벤드
110790          4.537000e+09    크리스에프앤씨
084650          4.513000e+09      랩지노믹스
294570          4.479000e+09         쿠콘
036200          4.434000e+09        유니셈
064290          3.930000e+09      인텍플러스
088800          3.621000e+09      에이스테크
287410          3.370000e+09    제이시스메디칼
067160          3.335000e+09     아프리카TV
122870          3.318000e+09  와이지엔터테인먼트
036830          3.295000e+09    솔브레인홀딩스
101160          3.225000e+09        월덱스
005290          2.904000e+09      동진쎄미켐
228670          2.810000e+09         레이
086900          2.762000e+09       메디톡스
065350          2.721000e+09     신성델타테크
131390          2.716000e+09      원익피앤이
101490          2.557000e+09     에스앤에스텍
096240          2.511000e+09       청담러닝
230360          2.458000e+09      에코마케팅
028300          2.431000e+09      에이치엘비
121600          2.402000e+09      나노신소재
051160          2.393000e+09      지어소프트
091990          2.326000e+09   셀트리온헬스케어
068240          2.275000e+09       다원시스
137950          2.239000e+09     제이씨케미칼
064260          2.211000e+09         다날
270870          2.197000e+09        뉴트리
063170          2.172000e+09       서울옥션
126340          2.065000e+09        비나텍

In [93]:
rank_50_list = list(rank_pension_amount_df['stock_name'].head(50).values)
common_50_list = [sn for sn in rank_50_list if sn in rank_pension_portion_df['stock_name'].head(50).values]

In [94]:
len(common_50_list)

39

In [95]:
common_50_list

['에코프로',
 '에스티팜',
 '천보',
 '심텍',
 '카페24',
 '이녹스첨단소재',
 '파마리서치',
 '덕산테코피아',
 '인터로조',
 '덕산네오룩스',
 '동화기업',
 '메드팩토',
 '테스나',
 '유진테크',
 '더네이쳐홀딩스',
 '태광',
 '티에스이',
 '성광벤드',
 '크리스에프앤씨',
 '랩지노믹스',
 '쿠콘',
 '유니셈',
 '인텍플러스',
 '에이스테크',
 '제이시스메디칼',
 '솔브레인홀딩스',
 '월덱스',
 '레이',
 '신성델타테크',
 '원익피앤이',
 '에스앤에스텍',
 '청담러닝',
 '나노신소재',
 '지어소프트',
 '제이씨케미칼',
 '다날',
 '뉴트리',
 '서울옥션',
 '비나텍']